# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /mnt/akademie_storage/crispasr

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /mnt/akademie_storage/crispasr

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running tests..."
	/usr/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test
.PHONY : test/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/akademie_storage/crispasr/CMakeFiles /mnt/akademie_storage/crispasr//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/akademie_storage/crispasr/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Experimental

# Build rule for target.
Experimental: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Experimental
.PHONY : Experimental

# fast build rule for target.
Experimental/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Experimental.dir/build.make CMakeFiles/Experimental.dir/build
.PHONY : Experimental/fast

#=============================================================================
# Target rules for targets named Nightly

# Build rule for target.
Nightly: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Nightly
.PHONY : Nightly

# fast build rule for target.
Nightly/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Nightly.dir/build.make CMakeFiles/Nightly.dir/build
.PHONY : Nightly/fast

#=============================================================================
# Target rules for targets named Continuous

# Build rule for target.
Continuous: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Continuous
.PHONY : Continuous

# fast build rule for target.
Continuous/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Continuous.dir/build.make CMakeFiles/Continuous.dir/build
.PHONY : Continuous/fast

#=============================================================================
# Target rules for targets named NightlyMemoryCheck

# Build rule for target.
NightlyMemoryCheck: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyMemoryCheck
.PHONY : NightlyMemoryCheck

# fast build rule for target.
NightlyMemoryCheck/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NightlyMemoryCheck.dir/build.make CMakeFiles/NightlyMemoryCheck.dir/build
.PHONY : NightlyMemoryCheck/fast

#=============================================================================
# Target rules for targets named NightlyStart

# Build rule for target.
NightlyStart: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyStart
.PHONY : NightlyStart

# fast build rule for target.
NightlyStart/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NightlyStart.dir/build.make CMakeFiles/NightlyStart.dir/build
.PHONY : NightlyStart/fast

#=============================================================================
# Target rules for targets named NightlyUpdate

# Build rule for target.
NightlyUpdate: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyUpdate
.PHONY : NightlyUpdate

# fast build rule for target.
NightlyUpdate/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NightlyUpdate.dir/build.make CMakeFiles/NightlyUpdate.dir/build
.PHONY : NightlyUpdate/fast

#=============================================================================
# Target rules for targets named NightlyConfigure

# Build rule for target.
NightlyConfigure: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyConfigure
.PHONY : NightlyConfigure

# fast build rule for target.
NightlyConfigure/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NightlyConfigure.dir/build.make CMakeFiles/NightlyConfigure.dir/build
.PHONY : NightlyConfigure/fast

#=============================================================================
# Target rules for targets named NightlyBuild

# Build rule for target.
NightlyBuild: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyBuild
.PHONY : NightlyBuild

# fast build rule for target.
NightlyBuild/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NightlyBuild.dir/build.make CMakeFiles/NightlyBuild.dir/build
.PHONY : NightlyBuild/fast

#=============================================================================
# Target rules for targets named NightlyTest

# Build rule for target.
NightlyTest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyTest
.PHONY : NightlyTest

# fast build rule for target.
NightlyTest/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NightlyTest.dir/build.make CMakeFiles/NightlyTest.dir/build
.PHONY : NightlyTest/fast

#=============================================================================
# Target rules for targets named NightlyCoverage

# Build rule for target.
NightlyCoverage: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyCoverage
.PHONY : NightlyCoverage

# fast build rule for target.
NightlyCoverage/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NightlyCoverage.dir/build.make CMakeFiles/NightlyCoverage.dir/build
.PHONY : NightlyCoverage/fast

#=============================================================================
# Target rules for targets named NightlyMemCheck

# Build rule for target.
NightlyMemCheck: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyMemCheck
.PHONY : NightlyMemCheck

# fast build rule for target.
NightlyMemCheck/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NightlyMemCheck.dir/build.make CMakeFiles/NightlyMemCheck.dir/build
.PHONY : NightlyMemCheck/fast

#=============================================================================
# Target rules for targets named NightlySubmit

# Build rule for target.
NightlySubmit: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlySubmit
.PHONY : NightlySubmit

# fast build rule for target.
NightlySubmit/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NightlySubmit.dir/build.make CMakeFiles/NightlySubmit.dir/build
.PHONY : NightlySubmit/fast

#=============================================================================
# Target rules for targets named ExperimentalStart

# Build rule for target.
ExperimentalStart: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalStart
.PHONY : ExperimentalStart

# fast build rule for target.
ExperimentalStart/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ExperimentalStart.dir/build.make CMakeFiles/ExperimentalStart.dir/build
.PHONY : ExperimentalStart/fast

#=============================================================================
# Target rules for targets named ExperimentalUpdate

# Build rule for target.
ExperimentalUpdate: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalUpdate
.PHONY : ExperimentalUpdate

# fast build rule for target.
ExperimentalUpdate/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ExperimentalUpdate.dir/build.make CMakeFiles/ExperimentalUpdate.dir/build
.PHONY : ExperimentalUpdate/fast

#=============================================================================
# Target rules for targets named ExperimentalConfigure

# Build rule for target.
ExperimentalConfigure: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalConfigure
.PHONY : ExperimentalConfigure

# fast build rule for target.
ExperimentalConfigure/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ExperimentalConfigure.dir/build.make CMakeFiles/ExperimentalConfigure.dir/build
.PHONY : ExperimentalConfigure/fast

#=============================================================================
# Target rules for targets named ExperimentalBuild

# Build rule for target.
ExperimentalBuild: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalBuild
.PHONY : ExperimentalBuild

# fast build rule for target.
ExperimentalBuild/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ExperimentalBuild.dir/build.make CMakeFiles/ExperimentalBuild.dir/build
.PHONY : ExperimentalBuild/fast

#=============================================================================
# Target rules for targets named ExperimentalTest

# Build rule for target.
ExperimentalTest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalTest
.PHONY : ExperimentalTest

# fast build rule for target.
ExperimentalTest/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ExperimentalTest.dir/build.make CMakeFiles/ExperimentalTest.dir/build
.PHONY : ExperimentalTest/fast

#=============================================================================
# Target rules for targets named ExperimentalCoverage

# Build rule for target.
ExperimentalCoverage: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalCoverage
.PHONY : ExperimentalCoverage

# fast build rule for target.
ExperimentalCoverage/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ExperimentalCoverage.dir/build.make CMakeFiles/ExperimentalCoverage.dir/build
.PHONY : ExperimentalCoverage/fast

#=============================================================================
# Target rules for targets named ExperimentalMemCheck

# Build rule for target.
ExperimentalMemCheck: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalMemCheck
.PHONY : ExperimentalMemCheck

# fast build rule for target.
ExperimentalMemCheck/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ExperimentalMemCheck.dir/build.make CMakeFiles/ExperimentalMemCheck.dir/build
.PHONY : ExperimentalMemCheck/fast

#=============================================================================
# Target rules for targets named ExperimentalSubmit

# Build rule for target.
ExperimentalSubmit: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalSubmit
.PHONY : ExperimentalSubmit

# fast build rule for target.
ExperimentalSubmit/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ExperimentalSubmit.dir/build.make CMakeFiles/ExperimentalSubmit.dir/build
.PHONY : ExperimentalSubmit/fast

#=============================================================================
# Target rules for targets named ContinuousStart

# Build rule for target.
ContinuousStart: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousStart
.PHONY : ContinuousStart

# fast build rule for target.
ContinuousStart/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ContinuousStart.dir/build.make CMakeFiles/ContinuousStart.dir/build
.PHONY : ContinuousStart/fast

#=============================================================================
# Target rules for targets named ContinuousUpdate

# Build rule for target.
ContinuousUpdate: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousUpdate
.PHONY : ContinuousUpdate

# fast build rule for target.
ContinuousUpdate/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ContinuousUpdate.dir/build.make CMakeFiles/ContinuousUpdate.dir/build
.PHONY : ContinuousUpdate/fast

#=============================================================================
# Target rules for targets named ContinuousConfigure

# Build rule for target.
ContinuousConfigure: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousConfigure
.PHONY : ContinuousConfigure

# fast build rule for target.
ContinuousConfigure/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ContinuousConfigure.dir/build.make CMakeFiles/ContinuousConfigure.dir/build
.PHONY : ContinuousConfigure/fast

#=============================================================================
# Target rules for targets named ContinuousBuild

# Build rule for target.
ContinuousBuild: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousBuild
.PHONY : ContinuousBuild

# fast build rule for target.
ContinuousBuild/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ContinuousBuild.dir/build.make CMakeFiles/ContinuousBuild.dir/build
.PHONY : ContinuousBuild/fast

#=============================================================================
# Target rules for targets named ContinuousTest

# Build rule for target.
ContinuousTest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousTest
.PHONY : ContinuousTest

# fast build rule for target.
ContinuousTest/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ContinuousTest.dir/build.make CMakeFiles/ContinuousTest.dir/build
.PHONY : ContinuousTest/fast

#=============================================================================
# Target rules for targets named ContinuousCoverage

# Build rule for target.
ContinuousCoverage: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousCoverage
.PHONY : ContinuousCoverage

# fast build rule for target.
ContinuousCoverage/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ContinuousCoverage.dir/build.make CMakeFiles/ContinuousCoverage.dir/build
.PHONY : ContinuousCoverage/fast

#=============================================================================
# Target rules for targets named ContinuousMemCheck

# Build rule for target.
ContinuousMemCheck: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousMemCheck
.PHONY : ContinuousMemCheck

# fast build rule for target.
ContinuousMemCheck/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ContinuousMemCheck.dir/build.make CMakeFiles/ContinuousMemCheck.dir/build
.PHONY : ContinuousMemCheck/fast

#=============================================================================
# Target rules for targets named ContinuousSubmit

# Build rule for target.
ContinuousSubmit: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousSubmit
.PHONY : ContinuousSubmit

# fast build rule for target.
ContinuousSubmit/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ContinuousSubmit.dir/build.make CMakeFiles/ContinuousSubmit.dir/build
.PHONY : ContinuousSubmit/fast

#=============================================================================
# Target rules for targets named ggml-base

# Build rule for target.
ggml-base: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ggml-base
.PHONY : ggml-base

# fast build rule for target.
ggml-base/fast:
	$(MAKE) $(MAKESILENT) -f ggml/src/CMakeFiles/ggml-base.dir/build.make ggml/src/CMakeFiles/ggml-base.dir/build
.PHONY : ggml-base/fast

#=============================================================================
# Target rules for targets named ggml

# Build rule for target.
ggml: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ggml
.PHONY : ggml

# fast build rule for target.
ggml/fast:
	$(MAKE) $(MAKESILENT) -f ggml/src/CMakeFiles/ggml.dir/build.make ggml/src/CMakeFiles/ggml.dir/build
.PHONY : ggml/fast

#=============================================================================
# Target rules for targets named ggml-cpu

# Build rule for target.
ggml-cpu: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ggml-cpu
.PHONY : ggml-cpu

# fast build rule for target.
ggml-cpu/fast:
	$(MAKE) $(MAKESILENT) -f ggml/src/CMakeFiles/ggml-cpu.dir/build.make ggml/src/CMakeFiles/ggml-cpu.dir/build
.PHONY : ggml-cpu/fast

#=============================================================================
# Target rules for targets named whisper

# Build rule for target.
whisper: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 whisper
.PHONY : whisper

# fast build rule for target.
whisper/fast:
	$(MAKE) $(MAKESILENT) -f src/CMakeFiles/whisper.dir/build.make src/CMakeFiles/whisper.dir/build
.PHONY : whisper/fast

#=============================================================================
# Target rules for targets named cohere

# Build rule for target.
cohere: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 cohere
.PHONY : cohere

# fast build rule for target.
cohere/fast:
	$(MAKE) $(MAKESILENT) -f src/CMakeFiles/cohere.dir/build.make src/CMakeFiles/cohere.dir/build
.PHONY : cohere/fast

#=============================================================================
# Target rules for targets named canary

# Build rule for target.
canary: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 canary
.PHONY : canary

# fast build rule for target.
canary/fast:
	$(MAKE) $(MAKESILENT) -f src/CMakeFiles/canary.dir/build.make src/CMakeFiles/canary.dir/build
.PHONY : canary/fast

#=============================================================================
# Target rules for targets named canary_ctc

# Build rule for target.
canary_ctc: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 canary_ctc
.PHONY : canary_ctc

# fast build rule for target.
canary_ctc/fast:
	$(MAKE) $(MAKESILENT) -f src/CMakeFiles/canary_ctc.dir/build.make src/CMakeFiles/canary_ctc.dir/build
.PHONY : canary_ctc/fast

#=============================================================================
# Target rules for targets named parakeet

# Build rule for target.
parakeet: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 parakeet
.PHONY : parakeet

# fast build rule for target.
parakeet/fast:
	$(MAKE) $(MAKESILENT) -f src/CMakeFiles/parakeet.dir/build.make src/CMakeFiles/parakeet.dir/build
.PHONY : parakeet/fast

#=============================================================================
# Target rules for targets named qwen3_asr

# Build rule for target.
qwen3_asr: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 qwen3_asr
.PHONY : qwen3_asr

# fast build rule for target.
qwen3_asr/fast:
	$(MAKE) $(MAKESILENT) -f src/CMakeFiles/qwen3_asr.dir/build.make src/CMakeFiles/qwen3_asr.dir/build
.PHONY : qwen3_asr/fast

#=============================================================================
# Target rules for targets named voxtral

# Build rule for target.
voxtral: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 voxtral
.PHONY : voxtral

# fast build rule for target.
voxtral/fast:
	$(MAKE) $(MAKESILENT) -f src/CMakeFiles/voxtral.dir/build.make src/CMakeFiles/voxtral.dir/build
.PHONY : voxtral/fast

#=============================================================================
# Target rules for targets named voxtral4b

# Build rule for target.
voxtral4b: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 voxtral4b
.PHONY : voxtral4b

# fast build rule for target.
voxtral4b/fast:
	$(MAKE) $(MAKESILENT) -f src/CMakeFiles/voxtral4b.dir/build.make src/CMakeFiles/voxtral4b.dir/build
.PHONY : voxtral4b/fast

#=============================================================================
# Target rules for targets named granite_speech

# Build rule for target.
granite_speech: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 granite_speech
.PHONY : granite_speech

# fast build rule for target.
granite_speech/fast:
	$(MAKE) $(MAKESILENT) -f src/CMakeFiles/granite_speech.dir/build.make src/CMakeFiles/granite_speech.dir/build
.PHONY : granite_speech/fast

#=============================================================================
# Target rules for targets named wav2vec2-ggml

# Build rule for target.
wav2vec2-ggml: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 wav2vec2-ggml
.PHONY : wav2vec2-ggml

# fast build rule for target.
wav2vec2-ggml/fast:
	$(MAKE) $(MAKESILENT) -f src/CMakeFiles/wav2vec2-ggml.dir/build.make src/CMakeFiles/wav2vec2-ggml.dir/build
.PHONY : wav2vec2-ggml/fast

#=============================================================================
# Target rules for targets named ctc-align

# Build rule for target.
ctc-align: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ctc-align
.PHONY : ctc-align

# fast build rule for target.
ctc-align/fast:
	$(MAKE) $(MAKESILENT) -f src/CMakeFiles/ctc-align.dir/build.make src/CMakeFiles/ctc-align.dir/build
.PHONY : ctc-align/fast

#=============================================================================
# Target rules for targets named test-vad

# Build rule for target.
test-vad: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test-vad
.PHONY : test-vad

# fast build rule for target.
test-vad/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/test-vad.dir/build.make tests/CMakeFiles/test-vad.dir/build
.PHONY : test-vad/fast

#=============================================================================
# Target rules for targets named test-vad-full

# Build rule for target.
test-vad-full: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test-vad-full
.PHONY : test-vad-full

# fast build rule for target.
test-vad-full/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/test-vad-full.dir/build.make tests/CMakeFiles/test-vad-full.dir/build
.PHONY : test-vad-full/fast

#=============================================================================
# Target rules for targets named common

# Build rule for target.
common: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 common
.PHONY : common

# fast build rule for target.
common/fast:
	$(MAKE) $(MAKESILENT) -f examples/CMakeFiles/common.dir/build.make examples/CMakeFiles/common.dir/build
.PHONY : common/fast

#=============================================================================
# Target rules for targets named crispasr

# Build rule for target.
crispasr: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 crispasr
.PHONY : crispasr

# fast build rule for target.
crispasr/fast:
	$(MAKE) $(MAKESILENT) -f examples/cli/CMakeFiles/crispasr.dir/build.make examples/cli/CMakeFiles/crispasr.dir/build
.PHONY : crispasr/fast

#=============================================================================
# Target rules for targets named whisper-bench

# Build rule for target.
whisper-bench: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 whisper-bench
.PHONY : whisper-bench

# fast build rule for target.
whisper-bench/fast:
	$(MAKE) $(MAKESILENT) -f examples/bench/CMakeFiles/whisper-bench.dir/build.make examples/bench/CMakeFiles/whisper-bench.dir/build
.PHONY : whisper-bench/fast

#=============================================================================
# Target rules for targets named whisper-server

# Build rule for target.
whisper-server: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 whisper-server
.PHONY : whisper-server

# fast build rule for target.
whisper-server/fast:
	$(MAKE) $(MAKESILENT) -f examples/server/CMakeFiles/whisper-server.dir/build.make examples/server/CMakeFiles/whisper-server.dir/build
.PHONY : whisper-server/fast

#=============================================================================
# Target rules for targets named whisper-quantize

# Build rule for target.
whisper-quantize: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 whisper-quantize
.PHONY : whisper-quantize

# fast build rule for target.
whisper-quantize/fast:
	$(MAKE) $(MAKESILENT) -f examples/quantize/CMakeFiles/whisper-quantize.dir/build.make examples/quantize/CMakeFiles/whisper-quantize.dir/build
.PHONY : whisper-quantize/fast

#=============================================================================
# Target rules for targets named whisper-vad-speech-segments

# Build rule for target.
whisper-vad-speech-segments: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 whisper-vad-speech-segments
.PHONY : whisper-vad-speech-segments

# fast build rule for target.
whisper-vad-speech-segments/fast:
	$(MAKE) $(MAKESILENT) -f examples/vad-speech-segments/CMakeFiles/whisper-vad-speech-segments.dir/build.make examples/vad-speech-segments/CMakeFiles/whisper-vad-speech-segments.dir/build
.PHONY : whisper-vad-speech-segments/fast

#=============================================================================
# Target rules for targets named cohere-main

# Build rule for target.
cohere-main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 cohere-main
.PHONY : cohere-main

# fast build rule for target.
cohere-main/fast:
	$(MAKE) $(MAKESILENT) -f examples/cohere-main/CMakeFiles/cohere-main.dir/build.make examples/cohere-main/CMakeFiles/cohere-main.dir/build
.PHONY : cohere-main/fast

#=============================================================================
# Target rules for targets named cohere-quantize

# Build rule for target.
cohere-quantize: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 cohere-quantize
.PHONY : cohere-quantize

# fast build rule for target.
cohere-quantize/fast:
	$(MAKE) $(MAKESILENT) -f examples/cohere-main/CMakeFiles/cohere-quantize.dir/build.make examples/cohere-main/CMakeFiles/cohere-quantize.dir/build
.PHONY : cohere-quantize/fast

#=============================================================================
# Target rules for targets named cohere-align

# Build rule for target.
cohere-align: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 cohere-align
.PHONY : cohere-align

# fast build rule for target.
cohere-align/fast:
	$(MAKE) $(MAKESILENT) -f examples/cohere-align/CMakeFiles/cohere-align.dir/build.make examples/cohere-align/CMakeFiles/cohere-align.dir/build
.PHONY : cohere-align/fast

#=============================================================================
# Target rules for targets named parakeet-main

# Build rule for target.
parakeet-main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 parakeet-main
.PHONY : parakeet-main

# fast build rule for target.
parakeet-main/fast:
	$(MAKE) $(MAKESILENT) -f examples/parakeet-main/CMakeFiles/parakeet-main.dir/build.make examples/parakeet-main/CMakeFiles/parakeet-main.dir/build
.PHONY : parakeet-main/fast

#=============================================================================
# Target rules for targets named canary-main

# Build rule for target.
canary-main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 canary-main
.PHONY : canary-main

# fast build rule for target.
canary-main/fast:
	$(MAKE) $(MAKESILENT) -f examples/canary-main/CMakeFiles/canary-main.dir/build.make examples/canary-main/CMakeFiles/canary-main.dir/build
.PHONY : canary-main/fast

#=============================================================================
# Target rules for targets named nfa-align

# Build rule for target.
nfa-align: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 nfa-align
.PHONY : nfa-align

# fast build rule for target.
nfa-align/fast:
	$(MAKE) $(MAKESILENT) -f examples/nfa-align/CMakeFiles/nfa-align.dir/build.make examples/nfa-align/CMakeFiles/nfa-align.dir/build
.PHONY : nfa-align/fast

#=============================================================================
# Target rules for targets named qwen3-asr-test-conv

# Build rule for target.
qwen3-asr-test-conv: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 qwen3-asr-test-conv
.PHONY : qwen3-asr-test-conv

# fast build rule for target.
qwen3-asr-test-conv/fast:
	$(MAKE) $(MAKESILENT) -f examples/qwen3-asr-test-conv/CMakeFiles/qwen3-asr-test-conv.dir/build.make examples/qwen3-asr-test-conv/CMakeFiles/qwen3-asr-test-conv.dir/build
.PHONY : qwen3-asr-test-conv/fast

#=============================================================================
# Target rules for targets named qwen3-asr-test-llm

# Build rule for target.
qwen3-asr-test-llm: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 qwen3-asr-test-llm
.PHONY : qwen3-asr-test-llm

# fast build rule for target.
qwen3-asr-test-llm/fast:
	$(MAKE) $(MAKESILENT) -f examples/qwen3-asr-test-llm/CMakeFiles/qwen3-asr-test-llm.dir/build.make examples/qwen3-asr-test-llm/CMakeFiles/qwen3-asr-test-llm.dir/build
.PHONY : qwen3-asr-test-llm/fast

#=============================================================================
# Target rules for targets named qwen3-asr-test-trace

# Build rule for target.
qwen3-asr-test-trace: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 qwen3-asr-test-trace
.PHONY : qwen3-asr-test-trace

# fast build rule for target.
qwen3-asr-test-trace/fast:
	$(MAKE) $(MAKESILENT) -f examples/qwen3-asr-test-trace/CMakeFiles/qwen3-asr-test-trace.dir/build.make examples/qwen3-asr-test-trace/CMakeFiles/qwen3-asr-test-trace.dir/build
.PHONY : qwen3-asr-test-trace/fast

#=============================================================================
# Target rules for targets named qwen3-asr-test-bpe

# Build rule for target.
qwen3-asr-test-bpe: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 qwen3-asr-test-bpe
.PHONY : qwen3-asr-test-bpe

# fast build rule for target.
qwen3-asr-test-bpe/fast:
	$(MAKE) $(MAKESILENT) -f examples/qwen3-asr-test-bpe/CMakeFiles/qwen3-asr-test-bpe.dir/build.make examples/qwen3-asr-test-bpe/CMakeFiles/qwen3-asr-test-bpe.dir/build
.PHONY : qwen3-asr-test-bpe/fast

#=============================================================================
# Target rules for targets named qwen3-asr-main

# Build rule for target.
qwen3-asr-main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 qwen3-asr-main
.PHONY : qwen3-asr-main

# fast build rule for target.
qwen3-asr-main/fast:
	$(MAKE) $(MAKESILENT) -f examples/qwen3-asr-main/CMakeFiles/qwen3-asr-main.dir/build.make examples/qwen3-asr-main/CMakeFiles/qwen3-asr-main.dir/build
.PHONY : qwen3-asr-main/fast

#=============================================================================
# Target rules for targets named voxtral-test-llm

# Build rule for target.
voxtral-test-llm: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 voxtral-test-llm
.PHONY : voxtral-test-llm

# fast build rule for target.
voxtral-test-llm/fast:
	$(MAKE) $(MAKESILENT) -f examples/voxtral-test-llm/CMakeFiles/voxtral-test-llm.dir/build.make examples/voxtral-test-llm/CMakeFiles/voxtral-test-llm.dir/build
.PHONY : voxtral-test-llm/fast

#=============================================================================
# Target rules for targets named voxtral-test-encoder

# Build rule for target.
voxtral-test-encoder: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 voxtral-test-encoder
.PHONY : voxtral-test-encoder

# fast build rule for target.
voxtral-test-encoder/fast:
	$(MAKE) $(MAKESILENT) -f examples/voxtral-test-encoder/CMakeFiles/voxtral-test-encoder.dir/build.make examples/voxtral-test-encoder/CMakeFiles/voxtral-test-encoder.dir/build
.PHONY : voxtral-test-encoder/fast

#=============================================================================
# Target rules for targets named voxtral-test-e2e

# Build rule for target.
voxtral-test-e2e: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 voxtral-test-e2e
.PHONY : voxtral-test-e2e

# fast build rule for target.
voxtral-test-e2e/fast:
	$(MAKE) $(MAKESILENT) -f examples/voxtral-test-e2e/CMakeFiles/voxtral-test-e2e.dir/build.make examples/voxtral-test-e2e/CMakeFiles/voxtral-test-e2e.dir/build
.PHONY : voxtral-test-e2e/fast

#=============================================================================
# Target rules for targets named voxtral-main

# Build rule for target.
voxtral-main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 voxtral-main
.PHONY : voxtral-main

# fast build rule for target.
voxtral-main/fast:
	$(MAKE) $(MAKESILENT) -f examples/voxtral-main/CMakeFiles/voxtral-main.dir/build.make examples/voxtral-main/CMakeFiles/voxtral-main.dir/build
.PHONY : voxtral-main/fast

#=============================================================================
# Target rules for targets named voxtral4b-main

# Build rule for target.
voxtral4b-main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 voxtral4b-main
.PHONY : voxtral4b-main

# fast build rule for target.
voxtral4b-main/fast:
	$(MAKE) $(MAKESILENT) -f examples/voxtral4b-main/CMakeFiles/voxtral4b-main.dir/build.make examples/voxtral4b-main/CMakeFiles/voxtral4b-main.dir/build
.PHONY : voxtral4b-main/fast

#=============================================================================
# Target rules for targets named main

# Build rule for target.
main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 main
.PHONY : main

# fast build rule for target.
main/fast:
	$(MAKE) $(MAKESILENT) -f examples/deprecation-warning/CMakeFiles/main.dir/build.make examples/deprecation-warning/CMakeFiles/main.dir/build
.PHONY : main/fast

#=============================================================================
# Target rules for targets named bench

# Build rule for target.
bench: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 bench
.PHONY : bench

# fast build rule for target.
bench/fast:
	$(MAKE) $(MAKESILENT) -f examples/deprecation-warning/CMakeFiles/bench.dir/build.make examples/deprecation-warning/CMakeFiles/bench.dir/build
.PHONY : bench/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... Continuous"
	@echo "... ContinuousBuild"
	@echo "... ContinuousConfigure"
	@echo "... ContinuousCoverage"
	@echo "... ContinuousMemCheck"
	@echo "... ContinuousStart"
	@echo "... ContinuousSubmit"
	@echo "... ContinuousTest"
	@echo "... ContinuousUpdate"
	@echo "... Experimental"
	@echo "... ExperimentalBuild"
	@echo "... ExperimentalConfigure"
	@echo "... ExperimentalCoverage"
	@echo "... ExperimentalMemCheck"
	@echo "... ExperimentalStart"
	@echo "... ExperimentalSubmit"
	@echo "... ExperimentalTest"
	@echo "... ExperimentalUpdate"
	@echo "... Nightly"
	@echo "... NightlyBuild"
	@echo "... NightlyConfigure"
	@echo "... NightlyCoverage"
	@echo "... NightlyMemCheck"
	@echo "... NightlyMemoryCheck"
	@echo "... NightlyStart"
	@echo "... NightlySubmit"
	@echo "... NightlyTest"
	@echo "... NightlyUpdate"
	@echo "... bench"
	@echo "... canary"
	@echo "... canary-main"
	@echo "... canary_ctc"
	@echo "... cohere"
	@echo "... cohere-align"
	@echo "... cohere-main"
	@echo "... cohere-quantize"
	@echo "... common"
	@echo "... ctc-align"
	@echo "... ggml"
	@echo "... ggml-base"
	@echo "... ggml-cpu"
	@echo "... granite_speech"
	@echo "... main"
	@echo "... nfa-align"
	@echo "... parakeet"
	@echo "... parakeet-main"
	@echo "... qwen3-asr-main"
	@echo "... qwen3-asr-test-bpe"
	@echo "... qwen3-asr-test-conv"
	@echo "... qwen3-asr-test-llm"
	@echo "... qwen3-asr-test-trace"
	@echo "... qwen3_asr"
	@echo "... test-vad"
	@echo "... test-vad-full"
	@echo "... voxtral"
	@echo "... voxtral-main"
	@echo "... voxtral-test-e2e"
	@echo "... voxtral-test-encoder"
	@echo "... voxtral-test-llm"
	@echo "... voxtral4b"
	@echo "... voxtral4b-main"
	@echo "... wav2vec2-ggml"
	@echo "... whisper"
	@echo "... whisper-bench"
	@echo "... crispasr"
	@echo "... whisper-quantize"
	@echo "... whisper-server"
	@echo "... whisper-vad-speech-segments"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

