// test-core-gru.cpp — core/gru.h against a real PyTorch nn.GRU reference.
//
// The reference fixture is generated by tools/gen_gru_reference.py (PyTorch),
// which writes weights + input + expected output for a bidirectional GRU. Point
// CRISPASR_GRU_REF at it to run the parity case; without it that case skips, so
// CI stays green with no torch and no network.
//
// Why a real torch fixture rather than hand-rolled expectations: the two traps
// documented in core/gru.h — the reset gate multiplying the recurrent term
// (not h_{t-1}), and b_ih/b_hh not being foldable — both produce output that
// looks entirely reasonable. Only a byte-level comparison against PyTorch
// actually catches them. A hand-written expectation would encode whichever
// convention the author believed, which is exactly the thing under test.

#include "core/gru.h"

#include <catch2/catch_test_macros.hpp>
#include <catch2/matchers/catch_matchers_floating_point.hpp>

#include "ggml-alloc.h"
#include "ggml-backend.h"
#include "ggml-cpu.h"
#include "ggml.h"

#include <cmath>
#include <cstdio>
#include <cstdlib>
#include <vector>

namespace {

struct Fixture {
    int I = 0, H = 0, T = 0;
    std::vector<float> x; // (T, I)
    std::vector<float> w_ih_f, w_hh_f, b_ih_f, b_hh_f;
    std::vector<float> w_ih_r, w_hh_r, b_ih_r, b_hh_r;
    std::vector<float> expect; // (T, 2H)
    bool ok = false;
};

std::vector<float> read_n(FILE* f, size_t n) {
    std::vector<float> v(n);
    if (std::fread(v.data(), sizeof(float), n, f) != n)
        v.clear();
    return v;
}

Fixture load(const char* path) {
    Fixture fx;
    FILE* f = std::fopen(path, "rb");
    if (!f)
        return fx;
    int hdr[3];
    if (std::fread(hdr, sizeof(int), 3, f) != 3) {
        std::fclose(f);
        return fx;
    }
    fx.I = hdr[0];
    fx.H = hdr[1];
    fx.T = hdr[2];
    const size_t H3 = (size_t)3 * fx.H;
    fx.x = read_n(f, (size_t)fx.T * fx.I);
    fx.w_ih_f = read_n(f, H3 * fx.I);
    fx.w_hh_f = read_n(f, H3 * fx.H);
    fx.b_ih_f = read_n(f, H3);
    fx.b_hh_f = read_n(f, H3);
    fx.w_ih_r = read_n(f, H3 * fx.I);
    fx.w_hh_r = read_n(f, H3 * fx.H);
    fx.b_ih_r = read_n(f, H3);
    fx.b_hh_r = read_n(f, H3);
    fx.expect = read_n(f, (size_t)fx.T * 2 * fx.H);
    std::fclose(f);
    fx.ok = !fx.expect.empty() && !fx.w_ih_f.empty();
    return fx;
}

} // namespace

TEST_CASE("gru: bidirectional matches PyTorch nn.GRU", "[core][gru]") {
    const char* path = std::getenv("CRISPASR_GRU_REF");
    if (!path) {
        SUCCEED("CRISPASR_GRU_REF not set — skipping torch parity");
        return;
    }
    Fixture fx = load(path);
    REQUIRE(fx.ok);

    ggml_backend_t be = ggml_backend_cpu_init();
    REQUIRE(be != nullptr);

    const size_t nodes = 4096;
    ggml_init_params ip = {nodes * ggml_tensor_overhead() + ggml_graph_overhead_custom(nodes, false), nullptr, true};
    ggml_context* ctx = ggml_init(ip);
    REQUIRE(ctx != nullptr);
    ggml_cgraph* gf = ggml_new_graph_custom(ctx, nodes, false);

    const int I = fx.I, H = fx.H, T = fx.T, H3 = 3 * H;

    // torch weight_ih_l0 is (3H, I) row-major -> ggml ne = (I, 3H): mul_mat(W, x)
    // with x (I,T) then yields (3H, T), which is what gru_unidir expects.
    auto mk2 = [&](int64_t ne0, int64_t ne1) { return ggml_new_tensor_2d(ctx, GGML_TYPE_F32, ne0, ne1); };
    auto mk1 = [&](int64_t ne0) { return ggml_new_tensor_1d(ctx, GGML_TYPE_F32, ne0); };

    ggml_tensor* X = mk2(I, T);
    ggml_tensor *Wif = mk2(I, H3), *Whf = mk2(H, H3), *Bif = mk1(H3), *Bhf = mk1(H3);
    ggml_tensor *Wir = mk2(I, H3), *Whr = mk2(H, H3), *Bir = mk1(H3), *Bhr = mk1(H3);
    for (ggml_tensor* t : {X, Wif, Whf, Bif, Bhf, Wir, Whr, Bir, Bhr})
        ggml_set_input(t);

    ggml_tensor* out = core_gru::gru_bidir(ctx, gf, X, Wif, Whf, Bif, Bhf, Wir, Whr, Bir, Bhr, H);
    ggml_set_output(out);
    ggml_build_forward_expand(gf, out);

    ggml_gallocr_t ga = ggml_gallocr_new(ggml_backend_get_default_buffer_type(be));
    REQUIRE(ggml_gallocr_alloc_graph(ga, gf));

    auto up = [&](ggml_tensor* t, const std::vector<float>& v) {
        ggml_backend_tensor_set(t, v.data(), 0, v.size() * sizeof(float));
    };
    up(X, fx.x);
    up(Wif, fx.w_ih_f);
    up(Whf, fx.w_hh_f);
    up(Bif, fx.b_ih_f);
    up(Bhf, fx.b_hh_f);
    up(Wir, fx.w_ih_r);
    up(Whr, fx.w_hh_r);
    up(Bir, fx.b_ih_r);
    up(Bhr, fx.b_hh_r);

    REQUIRE(ggml_backend_graph_compute(be, gf) == GGML_STATUS_SUCCESS);

    std::vector<float> got((size_t)ggml_nelements(out));
    ggml_backend_tensor_get(out, got.data(), 0, got.size() * sizeof(float));
    REQUIRE(got.size() == fx.expect.size());

    double max_abs = 0.0;
    for (size_t i = 0; i < got.size(); i++)
        max_abs = std::max(max_abs, (double)std::fabs(got[i] - fx.expect[i]));
    INFO("max_abs vs torch = " << max_abs);
    REQUIRE(max_abs < 1e-5);

    ggml_gallocr_free(ga);
    ggml_free(ctx);
    ggml_backend_free(be);
}
