// tests/test-pinyin-g2p.cpp — parity of core_pinyin::convert_char_to_pinyin
// against F5-TTS's pypinyin-based reference (#294).
//
// Fixture tests/data/pinyin_parity.tsv is generated by tests/gen_pinyin_parity.py
// from the exact reference (pypinyin + jieba). We measure token-level accuracy
// and exact-sentence match; the path comes from the PINYIN_PARITY_TSV compile
// definition set in CMake.
#include <catch2/catch_test_macros.hpp>

#include "core/pinyin_g2p.h"

#include <cstdio>
#include <fstream>
#include <sstream>
#include <string>
#include <vector>

namespace {
std::vector<std::string> split(const std::string& s, char sep) {
    std::vector<std::string> out;
    std::string cur;
    for (char c : s) {
        if (c == sep) {
            out.push_back(cur);
            cur.clear();
        } else {
            cur += c;
        }
    }
    out.push_back(cur);
    return out;
}
} // namespace

TEST_CASE("pinyin g2p parity vs pypinyin reference", "[unit][pinyin]") {
    std::ifstream f(PINYIN_PARITY_TSV);
    REQUIRE(f.good()); // fixture must exist

    int n_sent = 0, n_exact = 0;
    long tok_total = 0, tok_match = 0;
    int printed = 0;

    std::string line;
    while (std::getline(f, line)) {
        if (line.empty())
            continue;
        auto tab = line.find('\t');
        REQUIRE(tab != std::string::npos);
        std::string input = line.substr(0, tab);
        std::vector<std::string> expected = split(line.substr(tab + 1), '\x1f');

        std::vector<std::string> got = core_pinyin::convert_char_to_pinyin(input);

        ++n_sent;
        bool exact = (got == expected);
        if (exact)
            ++n_exact;

        size_t m = std::min(got.size(), expected.size());
        for (size_t i = 0; i < m; ++i)
            if (got[i] == expected[i])
                ++tok_match;
        tok_total += (long)std::max(got.size(), expected.size());

        if (!exact && printed < 12) {
            ++printed;
            std::string e, g;
            for (auto& t : expected)
                e += (t == " " ? "_" : t) + "|";
            for (auto& t : got)
                g += (t == " " ? "_" : t) + "|";
            fprintf(stderr, "  MISMATCH  in='%s'\n    exp=%s\n    got=%s\n", input.c_str(), e.c_str(), g.c_str());
        }
    }

    double tok_acc = tok_total ? (double)tok_match / (double)tok_total : 0.0;
    double sent_acc = n_sent ? (double)n_exact / (double)n_sent : 0.0;
    fprintf(stderr, "pinyin g2p parity: sentences=%d exact=%d (%.1f%%)  token_acc=%ld/%ld (%.2f%%)\n", n_sent, n_exact,
            100.0 * sent_acc, tok_match, tok_total, 100.0 * tok_acc);

    REQUIRE(n_sent > 0);
    // Thresholds calibrated to the max-match ("min jieba") segmentation; exact
    // jieba parity is unattainable without embedding jieba's dictionary.
    CHECK(sent_acc >= 0.80);
    REQUIRE(tok_acc >= 0.95);
}

TEST_CASE("pinyin g2p: has_han + ascii passthrough is unaffected", "[unit][pinyin]") {
    CHECK(core_pinyin::has_han("hello world") == false);
    CHECK(core_pinyin::has_han("中文") == true);
    CHECK(core_pinyin::has_han("mix 中 text") == true);
    // A pure-ASCII string is not this function's job (f5_tts keeps its own
    // passthrough), but convert should still behave: every ascii char passes.
    auto t = core_pinyin::convert_char_to_pinyin("中A");
    REQUIRE(t.size() == 3); // " ", "zhong1", "A"
    CHECK(t[0] == " ");
    CHECK(t[1] == "zhong1");
    CHECK(t[2] == "A");
}
