// crispasr_tts_disclaimer.h — spoken AI-disclosure for voice-cloned TTS output.
//
// When voice cloning is used, a spoken disclaimer is prepended to the
// output: "This audio was generated by artificial intelligence." The
// disclaimer is synthesized at runtime using the loaded TTS backend
// with no voice reference (neutral/default voice — NOT the cloned
// voice), cached after first synthesis, and prepended with a 300ms
// silence gap.
//
// Header-only; thread-safe via std::call_once.

#pragma once

#include "crispasr_backend.h"
#include "whisper_params.h"

#include <mutex>
#include <string>
#include <vector>

namespace crispasr_disclaimer {

// The disclaimer text. Short, clear, factual.
inline const char* text() {
    return "This audio was generated by artificial intelligence.";
}

// Singleton cache: synthesized once, reused for every clone request.
struct cache {
    std::once_flag flag;
    std::vector<float> pcm;
    int sample_rate = 24000;
};

inline cache& get_cache() {
    static cache c;
    return c;
}

} // namespace crispasr_disclaimer

// Synthesize (or return cached) disclaimer PCM. Returns empty if the
// backend fails to synthesize without a voice reference. The caller
// prepends this to the cloned output.
//
// Thread-safe: multiple concurrent requests block on the first
// synthesis, then all get the cached result.
inline const std::vector<float>& crispasr_tts_get_disclaimer(CrispasrBackend* backend, const whisper_params& params) {
    auto& c = crispasr_disclaimer::get_cache();
    std::call_once(c.flag, [&]() {
        // Synthesize with no voice reference → default/neutral voice
        whisper_params neutral = params;
        neutral.tts_voice.clear();
        neutral.tts_instruct.clear();
        neutral.tts_speaker_id = 0;

        c.pcm = backend->synthesize(crispasr_disclaimer::text(), neutral);
        c.sample_rate = backend->tts_sample_rate();

        if (c.pcm.empty()) {
            fprintf(stderr, "crispasr: warning: could not synthesize disclaimer "
                            "(backend may not support voiceless synthesis); "
                            "voice-cloned output will not have a spoken disclaimer\n");
        } else {
            fprintf(stderr, "crispasr: disclaimer synthesized (%zu samples @ %d Hz, %.2fs)\n", c.pcm.size(),
                    c.sample_rate, (double)c.pcm.size() / (double)c.sample_rate);
        }
    });
    return c.pcm;
}

// Prepend disclaimer + silence gap to the given PCM vector. Modifies
// `audio` in-place. No-op if disclaimer is empty (synthesis failed).
inline void crispasr_tts_prepend_disclaimer(std::vector<float>& audio, CrispasrBackend* backend,
                                            const whisper_params& params) {
    const auto& disclaimer = crispasr_tts_get_disclaimer(backend, params);
    if (disclaimer.empty())
        return;

    const int sr = backend->tts_sample_rate();
    const int silence_n = sr * 3 / 10; // 300ms silence gap

    std::vector<float> prefixed;
    prefixed.reserve(disclaimer.size() + (size_t)silence_n + audio.size());
    prefixed.insert(prefixed.end(), disclaimer.begin(), disclaimer.end());
    prefixed.resize(prefixed.size() + (size_t)silence_n, 0.0f); // silence
    prefixed.insert(prefixed.end(), audio.begin(), audio.end());
    audio = std::move(prefixed);
}
