#!/usr/bin/env python3
"""
Acceptance test for MOSS-TTS-Local voice cloning (#249).

The question is not "does --voice run without crashing" — a reference spliced
into the wrong grid columns, or delay-shifted when it shouldn't be, runs fine and
produces confident audio in the DEFAULT voice. So the test is comparative:

  baseline = synth(text)                       # no reference
  cloned   = synth(text, voice=reference.wav)  # reference spliced in

Cloning is real only if the cloned output moves toward the reference speaker and
the baseline does not: sim(cloned, ref) must beat sim(baseline, ref) by a clear
margin. Speaker similarity is judged by resemblyzer — a third party, deliberately
not our own embedder, which would be grading its own homework.

Intelligibility is checked too (HARD RULE 3): a "clone" that captures the timbre
by destroying the words is not a pass, so both outputs are ASR'd and compared to
the requested text.

Follows the harness regime (clone in-kernel, import from the clone, heartbeat).
"""
import os, subprocess, sys, json, re
from pathlib import Path

WORK = Path("/kaggle/working")
TMP = Path("/kaggle/temp"); TMP.mkdir(parents=True, exist_ok=True)
REPO = TMP / "CrispASR"
BUILD = TMP / "build"
GGUF_REPO = "cstr/moss-tts-local-v1.5-GGUF"
BACKBONE = os.environ.get("MOSS_BACKBONE", "moss-tts-local-v1.5-q4_k.gguf")
CODEC = os.environ.get("MOSS_CODEC", "moss-tts-local-v1.5-codec-enc.gguf")
TEXT = ("The quick brown fox jumps over the lazy dog while the morning light "
        "spills across the empty street.")

if not REPO.exists():
    subprocess.run(["git", "clone", "--depth", "1", "--recurse-submodules",
                    "--shallow-submodules", "https://github.com/CrispStrobe/CrispASR.git", str(REPO)],
                   check=True, timeout=2400)

_h = REPO / "tools" / "kaggle"
sys.path.insert(0, str(_h if (_h / "kaggle_harness.py").exists() else Path(__file__).resolve().parent))
import kaggle_harness as kh  # noqa: E402

kh._HF_PROGRESS_PATH = "runs/moss-clone-accept-live.jsonl"
kh.init_progress()
res = {"text": TEXT, "backbone": BACKBONE, "codec": CODEC}


def sh(cmd, cwd=None, timeout=3600):
    print(f"$ {cmd}", flush=True)
    p = subprocess.run(cmd, shell=True, cwd=cwd, timeout=timeout,
                       stdout=subprocess.PIPE, stderr=subprocess.STDOUT, text=True)
    return p.returncode, p.stdout


kh.step("toolchain")
kh.install_build_toolchain()
token = kh.resolve_hf_token()
if token:
    os.environ["HF_TOKEN"] = token
    os.environ["HUGGING_FACE_HUB_TOKEN"] = token

# The 4B backbone generates autoregressively; on CPU a single utterance runs past
# the session limit, so this one needs the GPU.
cuda = kh.detect_cuda_arch()
kh.step("cmake", cuda_arch=cuda)
flags = ["-DCMAKE_BUILD_TYPE=Release", "-DCRISPASR_BUILD_TESTS=OFF",
         "-DCRISPASR_BUILD_EXAMPLES=ON", "-DCRISPASR_BUILD_SERVER=OFF",
         "-DGGML_CUDA=ON", f"-DCMAKE_CUDA_ARCHITECTURES={cuda}"] + kh.cache_and_link_flags()
with kh.build_heartbeat("cmake.configure"):
    rc, out = sh(f"cmake -S {REPO} -B {BUILD} -G Ninja " + " ".join(flags))
if rc != 0:
    print(out[-6000:], flush=True); raise SystemExit("configure failed")
with kh.build_heartbeat("cmake.build"):
    kh.sh_with_progress(f"stdbuf -oL -eL cmake --build {BUILD} --target crispasr-cli "
                        f"-j{kh.safe_build_jobs(gpu=True)}")
cli = BUILD / "bin" / "crispasr"
if not cli.exists():
    raise SystemExit("crispasr-cli missing after build")

kh.step("download models")
from huggingface_hub import hf_hub_download  # noqa: E402
backbone = hf_hub_download(repo_id=GGUF_REPO, filename=BACKBONE, token=token, local_dir=str(TMP / "gguf"))
codec = hf_hub_download(repo_id=GGUF_REPO, filename=CODEC, token=token, local_dir=str(TMP / "gguf"))
res["backbone_gb"] = round(Path(backbone).stat().st_size / 1e9, 2)
res["codec_gb"] = round(Path(codec).stat().st_size / 1e9, 2)
print(f"backbone {res['backbone_gb']} GB, codec {res['codec_gb']} GB", flush=True)

# JFK: a distinctive voice that no default TTS timbre resembles by accident, so a
# similarity gain cannot be luck. Its transcript is NOT the text we synthesize —
# otherwise a leak of the reference (the #310 failure mode) would read as success.
ref_wav = REPO / "samples" / "jfk.wav"

# --no-spoken-disclaimer, with the attestation it requires: cloned output gets an
# audible "This audio was generated by artificial intelligence" prefix, which the
# baseline does not. That prefix made the two arms incomparable in run 1 — it
# spoke in a different voice (polluting the similarity measurement) and added
# nine words the ASR faithfully transcribed (wer_cloned 0.3889 against 0.1111 for
# the baseline, on output that was otherwise verbatim). The inaudible watermark
# and C2PA provenance stay on; only the measurement contaminant goes.
common = (f"{cli} --backend moss-tts-local -m {backbone} --codec-model {codec} "
          f"--tts \"{TEXT}\" --seed 1234 --no-prints "
          f"--no-spoken-disclaimer --accept-marking-responsibility")


def synth(label, extra, timeout=5400):
    out_wav = TMP / f"moss_{label}.wav"
    with kh.build_heartbeat(f"synth.{label}", 30.0):
        rc, out = sh(f"{common} {extra} --tts-output {out_wav}", timeout=timeout)
    print(out[-4000:], flush=True)
    res[f"{label}_rc"] = rc
    res[f"{label}_log"] = out[-3000:]
    if rc == 0 and out_wav.exists():
        import shutil
        shutil.copy(str(out_wav), str(WORK / out_wav.name))  # for a human listen
        return out_wav
    return None


kh.step("synth baseline")
baseline = synth("baseline", "")
kh.step("synth cloned")
cloned = synth("cloned", f"--voice {ref_wav} --i-have-rights")

# ── speaker similarity, judged by a third party ────────────────────────────
kh.step("similarity")
sim = {}
try:
    rc, out = sh("pip install -q resemblyzer", timeout=900)
    from resemblyzer import VoiceEncoder, preprocess_wav  # noqa: E402
    import numpy as np  # noqa: E402
    # CPU: Kaggle's P100 is sm_60 and the installed torch wheel ships no kernels
    # for it ("no kernel image is available"), which killed the whole similarity
    # leg of run 1. The embeddings are tiny; the GPU buys nothing here.
    enc = VoiceEncoder(device="cpu")

    def embed(p):
        return enc.embed_utterance(preprocess_wav(Path(p)))

    e_ref = embed(ref_wav)
    for label, path in (("baseline", baseline), ("cloned", cloned)):
        if path:
            sim[label] = float(np.dot(embed(path), e_ref))
    print(f"similarity vs reference: {sim}", flush=True)
except Exception as e:  # noqa: BLE001
    sim["error"] = repr(e)
    print(f"similarity failed: {e!r}", flush=True)
res["similarity"] = sim

# ── intelligibility: the words must survive the clone ──────────────────────
kh.step("asr")


def norm(s):
    return " ".join(re.sub(r"[^a-z0-9 ]", " ", s.lower()).split())


def wer(ref, hyp):
    r, h = norm(ref).split(), norm(hyp).split()
    d = [[0] * (len(h) + 1) for _ in range(len(r) + 1)]
    for i in range(len(r) + 1):
        d[i][0] = i
    for j in range(len(h) + 1):
        d[0][j] = j
    for i in range(1, len(r) + 1):
        for j in range(1, len(h) + 1):
            d[i][j] = min(d[i - 1][j] + 1, d[i][j - 1] + 1,
                          d[i - 1][j - 1] + (r[i - 1] != h[j - 1]))
    return d[len(r)][len(h)] / max(1, len(r))


for label, path in (("baseline", baseline), ("cloned", cloned)):
    if not path:
        continue
    rc, out = sh(f"{cli} --backend parakeet -m auto --auto-download -f {path} --no-prints", timeout=3600)
    text = out.strip().splitlines()[-1] if out.strip() else ""
    res[f"asr_{label}"] = text
    res[f"wer_{label}"] = round(wer(TEXT, text), 4)
    print(f"[{label}] wer={res[f'wer_{label}']} :: {text}", flush=True)

# ── verdict ────────────────────────────────────────────────────────────────
# The margin, not the absolute number, is what decides: resemblyzer scores any
# two speech clips well above zero, so "cloned scores 0.7" proves nothing on its
# own. A reference that never reached the model leaves the two scores equal.
gain = None
if "baseline" in sim and "cloned" in sim:
    gain = round(sim["cloned"] - sim["baseline"], 4)
res["similarity_gain"] = gain
res["pass"] = bool(
    baseline and cloned
    and gain is not None and gain >= 0.05
    and res.get("wer_cloned", 1.0) <= 0.25
)
(WORK / "moss_clone_accept.json").write_text(json.dumps(res, indent=2))
kh.step("done", passed=res["pass"], gain=gain, wer_cloned=res.get("wer_cloned"))
print(json.dumps(res, indent=2), flush=True)
if not res["pass"]:
    raise SystemExit("acceptance test FAILED")
