// crispasr_wav_writer.h — header-only WAV (16-bit PCM) serializer
// plus the matching headerless raw-int16-LE emitter and MP3 ID3v2
// metadata helpers.
//
// Used by the TTS server route handler to wrap synthesised float32
// samples in either a self-contained RIFF blob (browsers, OpenAI
// `wav`) or a raw int16 LE byte stream (OpenAI `pcm`). Header-only
// so the unit tests can exercise both without linking the server
// translation unit.
//
// AI-generated provenance: all container formats (WAV, MP3) include
// metadata declaring the audio was generated by AI. WAV uses a
// LIST/INFO chunk (ISFT + ICMT); MP3 uses an ID3v2 TXXX frame.

#pragma once

#include <cmath>
#include <cstdint>
#include <cstring>
#include <string>

// ---------------------------------------------------------------------------
// WAV LIST/INFO chunk helpers (AI-provenance metadata)
// ---------------------------------------------------------------------------

// Append a single LIST/INFO sub-chunk to `out`. The 4-char `id` is the
// INFO key (ISFT, ICMT, ICRD, …) and `value` is a NUL-terminated C
// string. The sub-chunk is padded to an even byte boundary per the RIFF
// spec (the pad byte is NOT counted in the sub-chunk's size field).
inline void crispasr_wav_info_entry(std::string& out, const char id[4], const char* value) {
    auto put_u32 = [&](uint32_t v) {
        out.push_back((char)(v & 0xff));
        out.push_back((char)((v >> 8) & 0xff));
        out.push_back((char)((v >> 16) & 0xff));
        out.push_back((char)((v >> 24) & 0xff));
    };
    const uint32_t len = (uint32_t)std::strlen(value) + 1; // include NUL
    out.append(id, 4);
    put_u32(len);
    out.append(value, len);
    if (len & 1)
        out.push_back('\0'); // RIFF pad to even boundary
}

// Build the complete LIST/INFO chunk that marks this WAV as AI-generated.
// Returns the raw chunk bytes (caller patches the RIFF size to account
// for it). Fields:
//   ISFT — "CrispASR (AI-generated audio)"
//   ICMT — "This audio was synthesized by an AI text-to-speech model.
//           It is not a recording of a human speaker."
inline std::string crispasr_wav_make_info_chunk() {
    std::string body;
    body.append("INFO", 4);
    crispasr_wav_info_entry(body, "ISFT", "CrispASR (AI-generated audio)");
    crispasr_wav_info_entry(body, "ICMT",
                            "This audio was synthesized by an AI text-to-speech model. "
                            "It is not a recording of a human speaker.");

    // Wrap in LIST chunk header
    std::string chunk;
    chunk.reserve(8 + body.size());
    auto put_u32 = [&](uint32_t v) {
        chunk.push_back((char)(v & 0xff));
        chunk.push_back((char)((v >> 8) & 0xff));
        chunk.push_back((char)((v >> 16) & 0xff));
        chunk.push_back((char)((v >> 24) & 0xff));
    };
    chunk.append("LIST", 4);
    put_u32((uint32_t)body.size());
    chunk.append(body);
    return chunk;
}

// Build a 16-bit PCM RIFF WAV from float32 samples in [-1, 1]. Mono,
// `sample_rate` Hz. Samples outside [-1, 1] are clamped before the
// int16 conversion (avoids wraparound from std::lround). The header
// uses standard PCM format (1) and the little-endian byte order
// RFC 2361 prescribes — our serializer writes the bytes by hand so
// it's identical on both endian platforms.
//
// A LIST/INFO chunk is appended after the data chunk with AI-provenance
// metadata (ISFT, ICMT). The RIFF size accounts for both data and LIST.
inline std::string crispasr_make_wav_int16(const float* pcm, int n_samples, int sample_rate) {
    const uint16_t num_channels = 1;
    const uint16_t bits_per_sample = 16;
    const uint32_t byte_rate = (uint32_t)sample_rate * num_channels * (bits_per_sample / 8);
    const uint16_t block_align = num_channels * (bits_per_sample / 8);
    const uint32_t data_size = (uint32_t)(n_samples > 0 ? n_samples : 0) * block_align;

    // Build the LIST/INFO metadata chunk up front so we can account for
    // its size in the RIFF header.
    const std::string info_chunk = crispasr_wav_make_info_chunk();
    const uint32_t riff_size = 36 + data_size + (uint32_t)info_chunk.size();

    std::string out;
    out.reserve(44 + (size_t)data_size + info_chunk.size());
    auto put_u32 = [&](uint32_t v) {
        out.push_back((char)(v & 0xff));
        out.push_back((char)((v >> 8) & 0xff));
        out.push_back((char)((v >> 16) & 0xff));
        out.push_back((char)((v >> 24) & 0xff));
    };
    auto put_u16 = [&](uint16_t v) {
        out.push_back((char)(v & 0xff));
        out.push_back((char)((v >> 8) & 0xff));
    };
    out.append("RIFF", 4);
    put_u32(riff_size);
    out.append("WAVE", 4);
    out.append("fmt ", 4);
    put_u32(16); // PCM fmt chunk size
    put_u16(1);  // PCM format
    put_u16(num_channels);
    put_u32((uint32_t)sample_rate);
    put_u32(byte_rate);
    put_u16(block_align);
    put_u16(bits_per_sample);
    out.append("data", 4);
    put_u32(data_size);
    if (n_samples > 0) {
        out.resize(out.size() + (size_t)data_size);
        int16_t* dst = reinterpret_cast<int16_t*>(&out[out.size() - data_size]);
        for (int i = 0; i < n_samples; i++) {
            float s = pcm[i];
            if (s > 1.0f)
                s = 1.0f;
            if (s < -1.0f)
                s = -1.0f;
            dst[i] = (int16_t)std::lround(s * 32767.0f);
        }
    }
    // Append LIST/INFO metadata after the data chunk
    out.append(info_chunk);
    return out;
}

// Headerless raw int16 little-endian PCM. Same clamp+round semantics
// as the WAV writer above, just without the 44-byte RIFF prefix. This
// is what OpenAI's spec means by `response_format=pcm`: 24 kHz signed
// 16-bit LE mono raw bytes that the client interprets given out-of-band
// metadata (Content-Type plus the documented sample rate). Caller is
// responsible for passing the right sample rate semantics — the
// function itself doesn't encode rate (there's nowhere to put it).
inline std::string crispasr_make_pcm_int16_le(const float* pcm, int n_samples) {
    std::string out;
    if (n_samples <= 0)
        return out;
    out.resize((size_t)n_samples * 2);
    int16_t* dst = reinterpret_cast<int16_t*>(&out[0]);
    for (int i = 0; i < n_samples; i++) {
        float s = pcm[i];
        if (s > 1.0f)
            s = 1.0f;
        if (s < -1.0f)
            s = -1.0f;
        dst[i] = (int16_t)std::lround(s * 32767.0f);
    }
    // On a hypothetical big-endian host we'd byte-swap here; ggml only
    // ships LE platforms today, so the bytes are already wire-correct.
    return out;
}

// ---------------------------------------------------------------------------
// MP3 ID3v2 metadata (AI-provenance via TXXX frames)
// ---------------------------------------------------------------------------

// Build a minimal ID3v2.3 tag containing TXXX frames that mark the MP3
// as AI-generated. The caller prepends this to the raw LAME output.
//
// ID3v2.3 spec: https://id3.org/id3v2.3.0
//   Header: "ID3" + version (03 00) + flags (00) + 4-byte synchsafe size
//   Frame:  4-byte ID + 4-byte size + 2-byte flags + payload
//   TXXX:   encoding (00=latin1) + description + \0 + value
inline std::string crispasr_make_id3v2_ai_tag() {
    // Build frame payloads first, then wrap in ID3v2 header.
    auto make_txxx = [](const char* description, const char* value) -> std::string {
        std::string payload;
        payload.push_back('\x00'); // encoding: ISO-8859-1
        payload.append(description);
        payload.push_back('\x00'); // separator
        payload.append(value);
        // Frame header: "TXXX" + 4-byte BE size + 2-byte flags (0000)
        std::string frame;
        frame.append("TXXX", 4);
        uint32_t sz = (uint32_t)payload.size();
        frame.push_back((char)((sz >> 24) & 0xff));
        frame.push_back((char)((sz >> 16) & 0xff));
        frame.push_back((char)((sz >> 8) & 0xff));
        frame.push_back((char)(sz & 0xff));
        frame.push_back('\x00');
        frame.push_back('\x00'); // flags
        frame.append(payload);
        return frame;
    };

    std::string frames;
    frames.append(make_txxx("AI_GENERATED", "true"));
    frames.append(make_txxx("GENERATOR", "CrispASR"));
    frames.append(make_txxx("AI_CONTENT_NOTICE", "This audio was synthesized by an AI text-to-speech model. "
                                                 "It is not a recording of a human speaker."));

    // ID3v2.3 header (10 bytes)
    std::string tag;
    tag.reserve(10 + frames.size());
    tag.append("ID3", 3);
    tag.push_back('\x03'); // version 2.3
    tag.push_back('\x00'); // revision
    tag.push_back('\x00'); // flags (no unsync, no extended header)
    // Synchsafe size (28-bit, 7 bits per byte, MSB first)
    uint32_t sz = (uint32_t)frames.size();
    tag.push_back((char)((sz >> 21) & 0x7f));
    tag.push_back((char)((sz >> 14) & 0x7f));
    tag.push_back((char)((sz >> 7) & 0x7f));
    tag.push_back((char)(sz & 0x7f));
    tag.append(frames);
    return tag;
}
