// AUTO-GENERATED by tools/gen-omnivoice-instruct-map.py -- do not edit.
//
// Voice-design instruct vocabulary, mirrored from OmniVoice's
// omnivoice/utils/voice_design.py (k2-fsa/OmniVoice, Apache-2.0).
//
// One row per VALID item, in both languages. `counterpart` is the item's
// translation, or nullptr for accents (English-only) and dialects
// (Chinese-only). `group` is the mutual-exclusivity category index --
// upstream allows at most one item per category.
//
// Regenerate with: python tools/gen-omnivoice-instruct-map.py

#pragma once

namespace core_omnivoice_instruct {

struct InstructItem {
    const char* item;        // a valid instruct token (already lowercase)
    const char* counterpart; // its translation, or nullptr if it has none
    int group;               // mutual-exclusivity category
    bool is_zh;              // true when `item` is the Chinese form
};

inline constexpr InstructItem kInstructTable[] = {
    {"american accent", nullptr, 4, false},
    {"australian accent", nullptr, 4, false},
    {"british accent", nullptr, 4, false},
    {"canadian accent", nullptr, 4, false},
    {"child", "儿童", 1, false},
    {"chinese accent", nullptr, 4, false},
    {"elderly", "老年", 1, false},
    {"female", "女", 0, false},
    {"high pitch", "高音调", 2, false},
    {"indian accent", nullptr, 4, false},
    {"japanese accent", nullptr, 4, false},
    {"korean accent", nullptr, 4, false},
    {"low pitch", "低音调", 2, false},
    {"male", "男", 0, false},
    {"middle-aged", "中年", 1, false},
    {"moderate pitch", "中音调", 2, false},
    {"portuguese accent", nullptr, 4, false},
    {"russian accent", nullptr, 4, false},
    {"teenager", "少年", 1, false},
    {"very high pitch", "极高音调", 2, false},
    {"very low pitch", "极低音调", 2, false},
    {"whisper", "耳语", 3, false},
    {"young adult", "青年", 1, false},
    {"东北话", nullptr, 5, true},
    {"中年", "middle-aged", 1, true},
    {"中音调", "moderate pitch", 2, true},
    {"云南话", nullptr, 5, true},
    {"低音调", "low pitch", 2, true},
    {"儿童", "child", 1, true},
    {"四川话", nullptr, 5, true},
    {"女", "female", 0, true},
    {"宁夏话", nullptr, 5, true},
    {"少年", "teenager", 1, true},
    {"极低音调", "very low pitch", 2, true},
    {"极高音调", "very high pitch", 2, true},
    {"桂林话", nullptr, 5, true},
    {"河南话", nullptr, 5, true},
    {"济南话", nullptr, 5, true},
    {"甘肃话", nullptr, 5, true},
    {"男", "male", 0, true},
    {"石家庄话", nullptr, 5, true},
    {"老年", "elderly", 1, true},
    {"耳语", "whisper", 3, true},
    {"贵州话", nullptr, 5, true},
    {"陕西话", nullptr, 5, true},
    {"青岛话", nullptr, 5, true},
    {"青年", "young adult", 1, true},
    {"高音调", "high pitch", 2, true},
};

inline constexpr int kInstructTableN = 48;
inline constexpr int kInstructGroups = 6;

} // namespace core_omnivoice_instruct
