#!/usr/bin/env bash
# gen-default-cert-header.sh — (re)generate the bundled default C2PA cert and the
# embedded header src/core/crispasr_c2pa_default_cert.h.
#
# The bundled cert is a fixed, self-signed P-256/ES256 certificate baked into the
# binary so C2PA signing is on by default on EVERY platform (incl. the WASM
# browser sandbox and mobile, where no openssl/subprocess is available at
# runtime). The private key is intentionally PUBLIC — it only marks content as
# AI-generated (self-signed → "unverified signer"); it is not a trust anchor.
#
# Run from the repo root. Requires openssl + python3.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
CRT="$ROOT/assets/c2pa/crispasr-default-c2pa.crt"
KEY="$ROOT/assets/c2pa/crispasr-default-c2pa.key"
HDR="$ROOT/src/core/crispasr_c2pa_default_cert.h"
mkdir -p "$ROOT/assets/c2pa"

CNF="$(mktemp)"; trap 'rm -f "$CNF"' EXIT
cat > "$CNF" <<'CNF'
[req]
distinguished_name = dn
x509_extensions = v3
prompt = no
[dn]
CN = CrispASR (AI-generated, self-signed)
O = CrispASR
[v3]
basicConstraints = critical, CA:FALSE
keyUsage = critical, digitalSignature
extendedKeyUsage = critical, emailProtection
subjectKeyIdentifier = hash
authorityKeyIdentifier = keyid:always
CNF

openssl req -x509 -newkey ec -pkeyopt ec_paramgen_curve:P-256 -nodes -days 3650 \
    -keyout "$KEY" -out "$CRT" -config "$CNF"

python3 - "$CRT" "$KEY" "$HDR" <<'PY'
import sys
crt, key, hdr = open(sys.argv[1]).read(), open(sys.argv[2]).read(), sys.argv[3]
def raw(s): return 'R"C2PA(' + s + ')C2PA"'
open(hdr, "w").write(f'''// crispasr_c2pa_default_cert.h — GENERATED by scripts/gen-default-cert-header.sh.
// Do not edit by hand.
//
// A fixed, self-signed P-256/ES256 certificate + key baked into the binary so
// C2PA signing is on by default on EVERY platform, including the WASM browser
// sandbox and mobile where no openssl/subprocess is available. The private key
// is intentionally PUBLIC (it ships in the artifact): this only marks content as
// AI-generated in a machine-readable way (self-signed -> C2PA verifiers show
// "unverified signer"). It asserts nothing about identity and is NOT a trust
// anchor. For a TRUSTED signer identity, pass your own CA-issued cert via
// --c2pa-cert / --c2pa-key.
#pragma once

inline const char* crispasr_c2pa_default_cert_pem() {{
    return {raw(crt)};
}}
inline const char* crispasr_c2pa_default_key_pem() {{
    return {raw(key)};
}}
''')
print("wrote", hdr)
PY
echo "Regenerated $HDR"
