#!/usr/bin/env python3
"""gen-backend-caps-table.py — library-side backend capability table (#433).

`detect_backend()` answers "which backend loads this model" and nothing else, so
a caller learns the name and still cannot tell whether it can synthesise, do
speech-to-speech, or translate. The reporter's examples are exactly that: one
model file, one backend, several VERBS (voxcpm = TTS + S2S, gemma = ASR +
translate).

The capability data already exists and is already authoritative — every backend
adapter declares `capabilities()` and `--list-backends-json` prints it. The
problem is purely one of LOCATION: those adapters compile into the CLI
executable, not into libcrispasr, so no ABI consumer can reach them. Hoisting
77 adapters into the library is a large refactor for a lookup table.

So mirror it instead, the same way this repo already mirrors OmniVoice's
language map (tools/gen-omnivoice-lang-map.py -> src/core/omnivoice_lang_table.h,
with a CI drift check). The binary stays the single source of truth; this only
makes its answer linkable.

Regenerate with:
    python tools/gen-backend-caps-table.py [--crispasr ./build/bin/crispasr]
    python tools/gen-backend-caps-table.py --check     # exit 1 if stale
"""
from __future__ import annotations
import argparse, json, pathlib, subprocess, sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
OUT = ROOT / "src" / "core" / "backend_caps_table.h"

HEADER = """// AUTO-GENERATED by tools/gen-backend-caps-table.py -- do not edit.
//
// Backend name -> capability ("verb") list, mirrored from the CLI's
// `--list-backends-json`, which reads each adapter's capabilities(). The
// adapters live in examples/cli/ and compile into the crispasr executable, not
// into libcrispasr, so an ABI consumer cannot reach them directly (#433).
//
// The binary remains the source of truth; CI re-runs the generator and fails on
// drift, exactly as it does for omnivoice_lang_table.h.
//
// Regenerate with: python tools/gen-backend-caps-table.py

#pragma once

#include <cstdint>

namespace core_backend_caps {

struct BackendCaps {
    const char* name;      // backend id, as accepted by --backend
    uint32_t bits;         // CAP_* bitmask, as reported by the CLI
    const char* caps_csv;  // comma-separated capability names, stable order
};

static const BackendCaps k_backend_caps[] = {
"""

FOOTER = """};

static const int k_backend_caps_count = (int)(sizeof(k_backend_caps) / sizeof(k_backend_caps[0]));

} // namespace core_backend_caps
"""


def render(backends) -> str:
    rows = []
    for b in sorted(backends, key=lambda x: x.get("name", "")):
        name = b.get("name", "")
        bits = int(b.get("caps_bitmask", 0))
        caps = ",".join(b.get("caps", []))
        rows.append(f'    {{"{name}", {bits}u, "{caps}"}},')
    return HEADER + "\n".join(rows) + "\n" + FOOTER


def clang_format(text: str) -> str:
    """Run the repo's pinned clang-format over the rendered header.

    Without this the generator and tools/format.sh disagree: clang-format wraps
    the long capability strings and re-aligns the struct comments, so `--fix`
    would rewrite the file and the drift check would then call it stale. CI
    would fight itself, once per lint run, forever. Formatting here makes the
    two agree by construction rather than by my matching clang-format's
    line-breaking rules by hand.

    clang-format-18 specifically, matching tools/format.sh — a different major
    version reflows differently and would reintroduce the same disagreement.
    If it is absent the text is returned unformatted; the drift check then
    reports staleness, which is the correct loud outcome rather than a silent
    mismatch.
    """
    for exe in ("clang-format-18", "/opt/homebrew/opt/llvm@18/bin/clang-format"):
        try:
            r = subprocess.run([exe, "--assume-filename=backend_caps_table.h"],
                               input=text, capture_output=True, text=True)
            if r.returncode == 0 and r.stdout:
                return r.stdout
        except FileNotFoundError:
            continue
    print("gen-backend-caps-table: clang-format-18 not found; emitting unformatted",
          file=sys.stderr)
    return text


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--crispasr", default=str(ROOT / "build" / "bin" / "crispasr"))
    ap.add_argument("--check", action="store_true")
    a = ap.parse_args()

    binp = pathlib.Path(a.crispasr)
    if not binp.is_file():
        # A missing binary must not silently "pass" a drift check.
        print(f"gen-backend-caps-table: crispasr not found at {binp}", file=sys.stderr)
        return 0 if not a.check else 1
    r = subprocess.run([str(binp), "--list-backends-json"], capture_output=True, text=True)
    if r.returncode != 0:
        print(f"gen-backend-caps-table: --list-backends-json failed rc={r.returncode}", file=sys.stderr)
        return 1
    d = json.loads(r.stdout)
    backends = d if isinstance(d, list) else d.get("backends", [])
    if not backends:
        print("gen-backend-caps-table: no backends reported — refusing to write an empty table",
              file=sys.stderr)
        return 1
    text = clang_format(render(backends))

    if a.check:
        cur = OUT.read_text(encoding="utf-8") if OUT.is_file() else ""
        if cur != text:
            print(f"gen-backend-caps-table: {OUT.relative_to(ROOT)} is STALE "
                  f"({len(backends)} backends reported). Regenerate with "
                  f"`python tools/gen-backend-caps-table.py`.", file=sys.stderr)
            return 1
        print(f"backend caps table up to date ({len(backends)} backends)")
        return 0

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(text, encoding="utf-8")
    print(f"wrote {OUT} ({len(backends)} backends)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
