#!/usr/bin/env python
"""Regenerate the topic index at the top of LEARNINGS.md.

LEARNINGS.md is ~800 KB / 227 sections. Nobody reads it end to end, and an
agent that does not already know a lesson exists cannot grep for it — so the
file was effectively write-only. This builds a two-axis index at the top:

  * by TOPIC   — the transferable lesson, which is what most headings state
  * by MODEL   — a cross-reference, because a good half of the file is
                 per-model port notes and you usually arrive knowing the model

The index is GENERATED, never hand-edited: a hand-maintained index of a file
that grows weekly is a stale index by the second week (this repo has the scars
— see the "PLAN 'OPEN' items are frequently already shipped" lesson). Run
`--check` in CI to fail when it drifts.

    python tools/gen-learnings-index.py           # rewrite the block in place
    python tools/gen-learnings-index.py --check   # exit 1 if it is out of date

Section headings are the source of truth: `## <lesson> (<tag>)`. To move a
section to a different topic, add it to OVERRIDES below by its heading prefix.
"""

import re
import sys
from pathlib import Path

LEARNINGS = Path("LEARNINGS.md")
INDEX = Path("docs/LEARNINGS-INDEX.md")

# The index lives in its OWN file, not at the top of LEARNINGS.md, for two
# reasons: an index block containing `## ` headings gets re-parsed as sections
# on the next run (not idempotent), and inserting it shifts every line number
# the index itself cites. A pointer stub — with no headings in it — goes into
# LEARNINGS.md instead, so parsing and line numbers stay stable across runs.
BEGIN = "<!-- BEGIN INDEX POINTER — generated by tools/gen-learnings-index.py -->"
END = "<!-- END INDEX POINTER -->"

POINTER = f"""{BEGIN}
**Do not read this file top to bottom** — it is ~800 KB across {{n}} sections.
The generated topic + per-model index is [`docs/LEARNINGS-INDEX.md`](docs/LEARNINGS-INDEX.md).
Find the lesson there, then jump with `grep -n "<heading text>" LEARNINGS.md`.
Regenerate both with `python tools/gen-learnings-index.py` after adding a section.
{END}"""

# Ordered: first rule that matches wins, so put the narrow topics first.
TOPICS = [
    ("Security & untrusted input",
     r"untrusted|memory-safety|fuzzer|DoS|auth check|buffer from|parser that"),
    ("Compliance, provenance & marking (EU AI Act)",
     r"AI Act|consent|watermark|provenance|marking|attestation|C2PA|deep fake|"
     r"speaker.identity|disclosure|clone gate"),
    ("Build, CI, release & packaging",
     r"\bCI\b|workflow|release|tag is|cmake|cmake-js|linker|MSVC|Windows|cgo|LDFLAGS|ctest|"
     r"GitHub Action|compiler family|libcommon|HF Space|upload|Kaggle|crates|wheel|ccache|near-full disk"),
    ("Multi-surface wiring — CLI / C ABI / bindings / server",
     r"front-end|binding|C ABI|session|server|capability flag|surface|wrapper|WebSocket|"
     r"dry-run|resolver|--gpu-backend|silently ignored|API"),
    ("Parity, the diff harness & ground truth",
     r"diff.harness|parity|\bcos\b|cos_min|cos ?[01]\.|reference|blueprint|ground truth|dumper|"
     r"oracle|roundtrip|round-trip|teacher|argmax|logits-level|scale-invariant|input-align"),
    ("ggml graphs, allocation & caching",
     r"ggml_|gallocr|cgraph|scheduler|sched|graph|tensor|KV|broadcast|ggml view|rope_theta|siglu"),
    ("GPU portability — Metal / CUDA / Vulkan",
     r"Metal|CUDA|Vulkan|MoltenVK|\bGPU\b|coopmat|RDNA|WDDM|\bTDR\b|im2col|flash.attn|Ampere|thermal"),
    ("Quantization",
     r"quantiz|quantis|\bq4\b|\bq8\b|\bF16\b|f16|imatrix|bf16|sub-8-bit|Sub-8-bit"),
    ("Perf measurement & A/B discipline",
     r"perf|benchmark|\bRTF\b|dispatch|optimiz|faster|speed|slow run|micro-optim|sweet spot|"
     r"Best-of-N|measure the fraction|already been tried"),
    ("Long-form audio, VAD & chunking",
     r"\bVAD\b|chunk|long audio|long-form|long utterance|streaming|window"),
    ("Tokenizers, prompts, language & text",
     r"tokeniz|\bBPE\b|SentencePiece|Unigram|merges|prompt|\bLID\b|language|punctuation|"
     r"byte_fallback|instruction-echo|detokeniz|WER"),
    ("Mel, codecs & the audio front-end",
     r"\bmel\b|Mel|\bFFT\b|fbank|spectrogram|resampl|audio format|onset|codec|\bWAV\b|"
     r"conv|Conv1d|vocoder|RVQ|preprocessor"),
    ("Process, triage & documentation discipline",
     r"PLAN|issue|triage|handover|audit|discipline|docs|stale|roadmap|DRY|close-out|"
     r"already shipped|claim to VERIFY"),
]

# Roughly half the file is per-backend porting notes rather than transferable
# lessons. They get their own bucket instead of being forced into a topic — the
# model cross-reference below is how you actually find them.
PORTS = "Per-model port notes"

_M = "Multi-surface wiring — CLI / C ABI / bindings / server"
_P = "Parity, the diff harness & ground truth"
_G = "ggml graphs, allocation & caching"
_D = "Process, triage & documentation discipline"

# Heading-prefix -> topic, for the ones the keyword rules misfile.
OVERRIDES = {
    "A managed assembly and its native library cannot share a name": _M,
    "One red job hides every job behind it": _D,
    "A reference that shares the runtime's assumption": _P,
    "A positional arg landing on the WRONG parameter": _D,
    "Two writers on one output field": _M,
    "A feature has ~8 front-ends": _M,
    "Regression transcripts need WER tolerance": _P,
    "A guard has to assert the property the CONSUMER reads": _P,
    "Splitting a path in half drops its prologue and its epilogue": _M,
    "Deterministic DROPOUT of whole words/tokens": _P,
    "A converter that embeds a tokenizer MUST embed the merges": "Tokenizers, prompts, language & text",
    "A gate that ANDs": _M,
    "A hardcoded decode cap silently ignores": _M,
    "Backend-name guards must match": _M,
    "Server warmup is the launch-time differentiator": _M,
    "When a clone/zero-shot path misbehaves": _P,
    "A TTS AR model that \"never stops\"": _P,
    "An input feature the checkpoint wasn't trained with": _P,
    "Diff-harness \"drift\" is mostly the GGUF quant": _P,
    "Porting the missing sub-model is necessary": _P,
    "A `frames/token` (or chars/sec) length heuristic": _P,
    "Precomputed attention masks in a GGUF": _G,
    "A byte-identical standalone reproducer": _G,
    "Asymmetric rel-pos shift": _G,
    "Decompose ConvTranspose1d": _G,
    "ggml / inference engine": _G,
    "2026-05-05 — ggml fork patches we carry": _G,
    "Quantisation and memory": "Quantization",
    "Quantization": "Quantization",
    "CPU vs ONNX vs PyTorch baselines": "Perf measurement & A/B discipline",
    "Cross-backend bug-sweep methodology": "Perf measurement & A/B discipline",
    "Audio format lessons": "Mel, codecs & the audio front-end",
    "Language handling": "Tokenizers, prompts, language & text",
    "Model architecture comparisons": PORTS,
    "Specific bugs that cost us a day each": _D,
    "Audit script ≠ behavior test": _D,
    "`git apply --3way` STAGES its result": _D,
    "#311 --strict-pipeline SHIPPED": _M,
    "glint MP3+AAC TTS output": "Mel, codecs & the audio front-end",
    "indextts long-ref crash FIXED": PORTS,
    "PR #244 dequant-cache fix MERGED": _G,
}

# Families to cross-reference. Order matters only for readability.
MODELS = [
    ("chatterbox", r"[Cc]hatterbox|CAMPPlus|S3Tokenizer|S3Gen|HiFT"),
    ("cosyvoice3", r"cosyvoice|CosyVoice|CFM Euler"),
    ("vibevoice", r"vibevoice|VibeVoice"),
    ("tada", r"\bTADA\b|\btada\b"),
    ("whisper", r"[Ww]hisper"),
    ("parakeet / TDT", r"[Pp]arakeet|\bTDT\b|MAES"),
    ("moss", r"MOSS|moss"),
    ("firered", r"FireRed|firered"),
    ("funasr / sensevoice / SANM", r"FunASR|funasr|SenseVoice|SANM"),
    ("kyutai / moshi / mimi", r"Kyutai|moshi|Mimi|CSM"),
    ("dia", r"\bDia\b"),
    ("parler", r"Parler"),
    ("speecht5", r"SpeechT5"),
    ("bark", r"Bark TTS"),
    ("pocket-tts", r"Pocket TTS|pocket_tts"),
    ("melotts / VITS", r"MeloTTS|melotts|VITS"),
    ("fastpitch", r"FastPitch"),
    ("indextts", r"IndexTTS"),
    ("orpheus / SNAC", r"Orpheus|SNAC"),
    ("voxcpm2", r"voxcpm2"),
    ("openvoice2", r"OpenVoice2"),
    ("glm-asr", r"glm-asr"),
    ("qwen3", r"Qwen3|qwen3"),
    ("madlad / T5", r"MADLAD|T5-family"),
    ("mini-omni2", r"Mini-Omni2"),
    ("titanet / speaker-id", r"TitaNet|Speaker verification"),
    ("audioseal", r"AudioSeal"),
    ("cohere", r"\b[Cc]ohere\b"),  # \b matters: bare "cohere" also matches "coherent"
    ("voxtral", r"[Vv]oxtral"),
    ("granite", r"[Gg]ranite"),
    ("ark-asr", r"ARK-ASR|ark[-_]asr|arkasr"),
    ("higgs-stt", r"[Hh]iggs"),
    ("dots-tts", r"dots\.tts|dots-tts|dots_tts"),
    ("irodori", r"[Ii]rodori"),
    ("f5-tts", r"F5-TTS|f5-tts|f5_tts"),
    ("kokoro", r"[Kk]okoro"),
    ("kugelaudio", r"[Kk]ugelaudio"),
    ("zonos", r"[Zz]onos"),
    ("omniasr / omnivoice", r"[Oo]mniASR|omniasr|[Oo]mniVoice|omnivoice"),
    ("glm / mimo / mega", r"glm-asr|mimo[-_]asr|mega[-_]asr"),
]


def sections(text):
    lines = text.splitlines()
    out = []
    for i, line in enumerate(lines, 1):
        m = re.match(r"^## (.+?)\s*$", line)
        if not m:
            continue
        h = m.group(1)
        tm = re.search(r"\(([^()]*\d{4}(?:-\d{2}-\d{2})?)\)\s*$", h)
        lesson = h[: tm.start()].rstrip() if tm else h
        out.append({"line": i, "heading": h, "lesson": lesson})
    # Attach each section's body — the model cross-reference keys off the body,
    # because a section is usually *about* a model that its heading never names.
    for k, s in enumerate(out):
        end = out[k + 1]["line"] - 1 if k + 1 < len(out) else len(lines)
        s["body"] = "\n".join(lines[s["line"] : end])
    return out


# A section counts for a family if its heading names it, or its body mentions it
# this many times — enough to mean "substantially about", not a passing mention.
BODY_MENTIONS = 3


def in_family(sec, pat):
    if re.search(pat, sec["heading"]):
        return True
    return len(re.findall(pat, sec["body"])) >= BODY_MENTIONS


def topic_of(sec):
    for prefix, t in OVERRIDES.items():
        if sec["heading"].startswith(prefix):
            return t
    for name, pat in TOPICS:
        if re.search(pat, sec["heading"]):
            return name
    # Not a transferable lesson but it names a backend → it is a port note.
    if any(re.search(pat, sec["heading"]) for _, pat in MODELS):
        return PORTS
    return "Uncategorised"


def build_index(secs):
    for s in secs:
        s["topic"] = topic_of(s)

    order = [n for n, _ in TOPICS] + [PORTS, "Uncategorised"]
    lines = ["# LEARNINGS.md — index",
             "",
             "GENERATED by `tools/gen-learnings-index.py`. Do not hand-edit; re-run it.",
             "",
             "`LEARNINGS.md` is ~800 KB and nobody reads it whole. Scan this index, then jump:",
             "",
             "```bash",
             'grep -n "<heading text>" LEARNINGS.md   # then Read with that offset',
             "```",
             "",
             "Every heading states its lesson in full, so **the index is the summary** — if a",
             "line does not sound relevant, neither is the section under it. `L<n>` is the line",
             "in LEARNINGS.md at generation time; re-run the tool if the numbers look off.",
             "",
             "Roughly half the file is transferable method (the topic groups) and half is",
             "per-backend porting detail (Per-model port notes + the family cross-reference).",
             "Reach for the topic groups when you are stuck on a *technique*, and the",
             "cross-reference when you already know which model you are touching.",
             ""]

    lines += [f"## Index by topic ({len(secs)} lessons)", ""]
    for t in order:
        group = [s for s in secs if s["topic"] == t]
        if not group:
            continue
        lines.append(f"**{t}** ({len(group)})")
        lines.append("")
        for s in group:
            lines.append(f"- L{s['line']} — {s['lesson']}")
        lines.append("")

    lines += ["## Cross-reference by model / family", "",
              "A section is listed when its heading names the family, or its body mentions it",
              f"at least {BODY_MENTIONS} times. Sections appear under several families; this is a",
              "lookup, not a partition.",
              ""]
    for name, pat in MODELS:
        hits = [s for s in secs if in_family(s, pat)]
        if not hits:
            continue
        lines.append(f"- **{name}** ({len(hits)}) — " + ", ".join(f"L{s['line']}" for s in hits))
    lines.append("")
    return "\n".join(lines)


def main():
    text = LEARNINGS.read_text()

    # 1. Put the pointer in place FIRST, then read line numbers off the result —
    #    otherwise the insertion shifts every number the index is about to cite.
    n = len(sections(text))
    pointer = POINTER.format(n=n)
    if BEGIN in text:
        pre, rest = text.split(BEGIN, 1)
        _, post = rest.split(END, 1)
        new_learnings = pre + pointer + post
    else:
        marker = "\n---\n"
        i = text.index(marker) + len(marker)
        new_learnings = text[:i] + "\n" + pointer + "\n" + text[i:]

    # 2. Sections, with their final line numbers.
    secs = sections(new_learnings)
    if not secs:
        sys.exit("no '## ' sections found — wrong file?")
    index = build_index(secs)

    if "--check" in sys.argv:
        stale = []
        if new_learnings != text:
            stale.append("LEARNINGS.md pointer")
        if not INDEX.exists() or INDEX.read_text() != index:
            stale.append(str(INDEX))
        if stale:
            sys.exit(f"out of date: {', '.join(stale)} — run: python tools/gen-learnings-index.py")
        print(f"LEARNINGS index up to date ({len(secs)} sections)")
        return

    if new_learnings != text:
        LEARNINGS.write_text(new_learnings)
    INDEX.parent.mkdir(parents=True, exist_ok=True)
    INDEX.write_text(index)

    uncat = [s for s in secs if s["topic"] == "Uncategorised"]
    print(f"indexed {len(secs)} sections -> {INDEX} ({len(index)} bytes)")
    for t in [n for n, _ in TOPICS] + [PORTS]:
        c = sum(1 for s in secs if s["topic"] == t)
        if c:
            print(f"   {c:3}  {t}")
    if uncat:
        print(f"{len(uncat)} UNCATEGORISED — add a rule or an OVERRIDES entry:")
        for s in uncat:
            print(f"   L{s['line']} {s['lesson'][:88]}")


if __name__ == "__main__":
    main()
