#!/usr/bin/env python
"""Generate src/core/omnivoice_lang_table.h from OmniVoice's lang_map.py.

The OmniVoice prompt carries the target language as a literal string between
``<|lang_start|>`` and ``<|lang_end|>``, and the model was trained on the ISO
639-3 IDs in ``omnivoice/utils/lang_map.py`` -- not on English names and not on
BCP-47 tags. ``OmniVoice.generate()`` runs every user-supplied value through
``_resolve_language()`` before it reaches the prompt; we mirror that resolver in
``src/core/omnivoice_lang.h`` and generate its table here so the two cannot
drift by hand-editing.

The source is VENDORED at ``third_party/omnivoice/lang_map.py`` (byte-identical
to upstream) so that ``--check`` is hermetic: a gate that needs the network is a
gate that goes flaky and then gets disabled. Upstream drift is a separate,
best-effort question -- ``--check-upstream`` answers it by comparing git blob
hashes against the GitHub API, and only that step needs a network.

Usage:
    python tools/gen-omnivoice-lang-map.py             # regenerate from vendored
    python tools/gen-omnivoice-lang-map.py --check     # hermetic; what CI gates on
    python tools/gen-omnivoice-lang-map.py --check-upstream   # advisory drift check
    python tools/gen-omnivoice-lang-map.py --update-vendored  # take a new revision
    python tools/gen-omnivoice-lang-map.py --source /path/to/lang_map.py
"""

import argparse
import ast
import hashlib
import json
import pathlib
import sys
import urllib.request

UPSTREAM_RAW = (
    "https://raw.githubusercontent.com/k2-fsa/OmniVoice/main/"
    "omnivoice/utils/lang_map.py"
)
UPSTREAM_API = (
    "https://api.github.com/repos/k2-fsa/OmniVoice/contents/"
    "omnivoice/utils/lang_map.py"
)

HERE = pathlib.Path(__file__).resolve().parent
ROOT = HERE.parent
OUT = ROOT / "src" / "core" / "omnivoice_lang_table.h"
VENDORED = ROOT / "third_party" / "omnivoice" / "lang_map.py"


def git_blob_sha1(data: bytes) -> str:
    """git's object id for a blob — what the GitHub contents API returns as .sha."""
    h = hashlib.sha1()
    h.update(b"blob %d\0" % len(data))
    h.update(data)
    return h.hexdigest()


def load_mapping(source: str) -> dict:
    """Pull LANG_NAME_TO_ID out of lang_map.py without importing it."""
    if source.startswith("http://") or source.startswith("https://"):
        text = urllib.request.urlopen(source).read().decode("utf-8")
    else:
        text = pathlib.Path(source).read_text(encoding="utf-8")

    tree = ast.parse(text)
    for node in tree.body:
        if not isinstance(node, ast.Assign):
            continue
        if not any(
            isinstance(t, ast.Name) and t.id == "LANG_NAME_TO_ID"
            for t in node.targets
        ):
            continue
        # ast.literal_eval keeps this a data read, never an exec of the module.
        return ast.literal_eval(node.value)

    raise SystemExit(f"LANG_NAME_TO_ID not found in {source}")


def render(mapping: dict) -> str:
    # Sorted by name so the generated diff is reviewable and stable across runs;
    # the resolver builds its own hash indexes, so order carries no meaning.
    # Emitted unaligned on purpose: clang-format owns the layout of every
    # committed header, and a generator that padded columns would lose a
    # tools/format.sh --check fight with itself on the next regeneration.
    rows = sorted(mapping.items())

    lines = [
        "// AUTO-GENERATED by tools/gen-omnivoice-lang-map.py -- do not edit.",
        "//",
        "// Language name -> ISO 639-3 ID, mirrored from OmniVoice's",
        "// omnivoice/utils/lang_map.py (k2-fsa/OmniVoice, Apache-2.0). Names are",
        "// already lowercase upstream; the ID set is exactly the set of values, as",
        "// upstream's LANG_IDS = set(LANG_NAME_TO_ID.values()).",
        "//",
        "// Regenerate with: python tools/gen-omnivoice-lang-map.py",
        "",
        "#pragma once",
        "",
        "namespace core_omnivoice_lang {",
        "",
        "struct LangEntry {",
        "    const char* name; // lowercase English name",
        "    const char* id;   // ISO 639-3 code the model was trained on",
        "};",
        "",
        "inline constexpr LangEntry kLangTable[] = {",
    ]
    for name, code in rows:
        quoted = '"' + name.replace("\\", "\\\\").replace('"', '\\"') + '"'
        lines.append(f'    {{{quoted}, "{code}"}},')
    lines += [
        "};",
        "",
        f"inline constexpr int kLangTableN = {len(rows)};",
        "",
        "} // namespace core_omnivoice_lang",
        "",
    ]
    return "\n".join(lines)


def check_upstream() -> int:
    """Advisory: has upstream's lang_map.py moved since we vendored it?

    Compares git blob hashes, which is exact only because the vendored copy is
    byte-identical to upstream. Best-effort by design — a GitHub hiccup must not
    be able to red a lint run, so every failure mode here degrades to "skip".
    """
    local = git_blob_sha1(VENDORED.read_bytes())
    try:
        with urllib.request.urlopen(UPSTREAM_API, timeout=30) as r:
            remote = json.load(r)["sha"]
    except Exception as exc:  # network, rate limit, schema change — all advisory
        print(f"upstream drift check skipped ({type(exc).__name__}: {exc})")
        return 0

    if local == remote:
        print(f"third_party/omnivoice/lang_map.py: in sync with upstream ({local[:12]})")
        return 0

    print(
        f"NOTE: upstream lang_map.py has moved (vendored {local[:12]} != "
        f"upstream {remote[:12]}).\n"
        "      Take the new revision with: "
        "python tools/gen-omnivoice-lang-map.py --update-vendored\n"
        "      Read the diff before committing — a NEW language is an addition we "
        "want, but a CHANGED id for an existing name silently alters what every "
        "caller of that name synthesises."
    )
    return 0


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument(
        "--source",
        default=str(VENDORED),
        help="path or URL to lang_map.py (default: the vendored copy)",
    )
    ap.add_argument(
        "--check",
        action="store_true",
        help="hermetic: fail if the committed header differs from a fresh render",
    )
    ap.add_argument(
        "--check-upstream",
        action="store_true",
        help="advisory: report (never fail) if upstream lang_map.py has moved",
    )
    ap.add_argument(
        "--update-vendored",
        action="store_true",
        help="refetch upstream into third_party/ and regenerate the header",
    )
    args = ap.parse_args()

    if args.check_upstream:
        return check_upstream()

    source = args.source
    if args.update_vendored:
        data = urllib.request.urlopen(UPSTREAM_RAW, timeout=60).read()
        VENDORED.write_bytes(data)
        print(f"refetched {VENDORED} (blob {git_blob_sha1(data)})")
        print("→ update the hashes + date in third_party/omnivoice/README.md")
        source = str(VENDORED)

    rendered = render(load_mapping(source))

    if args.check:
        if not OUT.exists():
            print(f"{OUT} is missing", file=sys.stderr)
            return 1
        if OUT.read_text(encoding="utf-8") != rendered:
            print(
                f"{OUT} is stale -- run tools/gen-omnivoice-lang-map.py",
                file=sys.stderr,
            )
            return 1
        print(f"{OUT.name}: up to date ({len(load_mapping(source))} languages)")
        return 0

    OUT.write_text(rendered, encoding="utf-8")
    print(f"wrote {OUT} ({rendered.count(chr(10))} lines)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
