#!/usr/bin/env python
"""Generate src/core/omnivoice_instruct_table.h from OmniVoice's voice_design.py.

Sibling of tools/gen-omnivoice-lang-map.py, and for the same reason: the
OmniVoice prompt carries the voice-design instruct as a literal string between
``<|instruct_start|>`` and ``<|instruct_end|>``, drawn from a CLOSED 48-item
vocabulary. ``_resolve_instruct()`` lowercases, validates, translates EN<->ZH
and rejects anything else; a value that skips that pass is tokenized into
something the model never saw in that slot ('Male, British Accent' and
'male, british accent' share not one token id).

The source is VENDORED at third_party/omnivoice/voice_design.py (byte-identical
to upstream) so ``--check`` is hermetic.

Unlike the lang map, the vocabulary here is *derived* by loops at import time
(`_INSTRUCT_EN_TO_ZH`, `_INSTRUCT_MUTUALLY_EXCLUSIVE`, `_INSTRUCT_ALL_VALID` all
start empty and are filled from `_INSTRUCT_CATEGORIES`). Re-deriving those loops
here would be a second implementation to keep in sync -- exactly the drift this
generator exists to prevent -- so we import the vendored module and read the
results. It is a pure data module (one `re` import, no I/O, no side effects) that
we vendor and review, which is why executing it is acceptable where the lang
generator deliberately used ast.literal_eval.

Usage:
    python tools/gen-omnivoice-instruct-map.py             # regenerate
    python tools/gen-omnivoice-instruct-map.py --check     # hermetic; CI gates on this
    python tools/gen-omnivoice-instruct-map.py --update-vendored
"""

import argparse
import hashlib
import importlib.util
import json
import pathlib
import sys
import urllib.request

UPSTREAM_RAW = (
    "https://raw.githubusercontent.com/k2-fsa/OmniVoice/main/"
    "omnivoice/utils/voice_design.py"
)
UPSTREAM_API = (
    "https://api.github.com/repos/k2-fsa/OmniVoice/contents/"
    "omnivoice/utils/voice_design.py"
)

HERE = pathlib.Path(__file__).resolve().parent
ROOT = HERE.parent
OUT = ROOT / "src" / "core" / "omnivoice_instruct_table.h"
VENDORED = ROOT / "third_party" / "omnivoice" / "voice_design.py"


def git_blob_sha1(data: bytes) -> str:
    h = hashlib.sha1()
    h.update(b"blob %d\0" % len(data))
    h.update(data)
    return h.hexdigest()


def load_module(path: pathlib.Path):
    spec = importlib.util.spec_from_file_location("_ov_voice_design", path)
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


def has_cjk(s: str) -> bool:
    return any("一" <= c <= "鿿" for c in s)


def collect(mod):
    """Flatten the categories into one row per valid item.

    Each row carries its mutual-exclusivity GROUP (the index upstream builds in
    `_INSTRUCT_MUTUALLY_EXCLUSIVE`), its COUNTERPART in the other language (or
    None for accents/dialects, which exist in one language only), and whether
    the item itself is Chinese. Those three facts are everything
    `_resolve_instruct` needs: validation, EN<->ZH unification, conflict check.
    """
    rows = []
    for group, cat in enumerate(mod._INSTRUCT_CATEGORIES):
        if isinstance(cat, dict):
            for en, zh in cat.items():
                rows.append((en, zh, group, False))
                rows.append((zh, en, group, True))
        else:
            for item in sorted(cat):
                rows.append((item, None, group, has_cjk(item)))

    # Sanity: the flattened set must equal what upstream computed itself.
    assert {r[0] for r in rows} == set(mod._INSTRUCT_ALL_VALID), (
        "flattened items != _INSTRUCT_ALL_VALID — the derivation drifted"
    )
    # Sorted for a stable, reviewable diff; the resolver builds its own index.
    return sorted(rows), len(mod._INSTRUCT_CATEGORIES)


def render(rows, n_groups: int) -> str:
    lines = [
        "// AUTO-GENERATED by tools/gen-omnivoice-instruct-map.py -- do not edit.",
        "//",
        "// Voice-design instruct vocabulary, mirrored from OmniVoice's",
        "// omnivoice/utils/voice_design.py (k2-fsa/OmniVoice, Apache-2.0).",
        "//",
        "// One row per VALID item, in both languages. `counterpart` is the item's",
        "// translation, or nullptr for accents (English-only) and dialects",
        "// (Chinese-only). `group` is the mutual-exclusivity category index --",
        "// upstream allows at most one item per category.",
        "//",
        "// Regenerate with: python tools/gen-omnivoice-instruct-map.py",
        "",
        "#pragma once",
        "",
        "namespace core_omnivoice_instruct {",
        "",
        "struct InstructItem {",
        "    const char* item;        // a valid instruct token (already lowercase)",
        "    const char* counterpart; // its translation, or nullptr if it has none",
        "    int group;               // mutual-exclusivity category",
        "    bool is_zh;              // true when `item` is the Chinese form",
        "};",
        "",
        "inline constexpr InstructItem kInstructTable[] = {",
    ]
    for item, counterpart, group, is_zh in rows:
        cp = f'"{counterpart}"' if counterpart is not None else "nullptr"
        lines.append(f'    {{"{item}", {cp}, {group}, {str(is_zh).lower()}}},')
    lines += [
        "};",
        "",
        f"inline constexpr int kInstructTableN = {len(rows)};",
        f"inline constexpr int kInstructGroups = {n_groups};",
        "",
        "} // namespace core_omnivoice_instruct",
        "",
    ]
    return "\n".join(lines)


def check_upstream() -> int:
    local = git_blob_sha1(VENDORED.read_bytes())
    try:
        with urllib.request.urlopen(UPSTREAM_API, timeout=30) as r:
            remote = json.load(r)["sha"]
    except Exception as exc:
        print(f"upstream drift check skipped ({type(exc).__name__}: {exc})")
        return 0
    if local == remote:
        print(f"third_party/omnivoice/voice_design.py: in sync with upstream ({local[:12]})")
        return 0
    print(
        f"NOTE: upstream voice_design.py has moved (vendored {local[:12]} != "
        f"upstream {remote[:12]}).\n"
        "      Take it with: python tools/gen-omnivoice-instruct-map.py --update-vendored\n"
        "      Read the diff — a new accent is an addition we want, but a RENAMED "
        "item silently invalidates instructs that used to work."
    )
    return 0


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true", help="hermetic: fail if the header is stale")
    ap.add_argument("--check-upstream", action="store_true", help="advisory: report upstream drift")
    ap.add_argument("--update-vendored", action="store_true", help="refetch upstream, then regenerate")
    args = ap.parse_args()

    if args.check_upstream:
        return check_upstream()

    if args.update_vendored:
        data = urllib.request.urlopen(UPSTREAM_RAW, timeout=60).read()
        VENDORED.write_bytes(data)
        print(f"refetched {VENDORED} (blob {git_blob_sha1(data)})")
        print("→ update the hashes + date in third_party/omnivoice/README.md")

    rows, n_groups = collect(load_module(VENDORED))
    rendered = render(rows, n_groups)

    if args.check:
        if not OUT.exists():
            print(f"{OUT} is missing", file=sys.stderr)
            return 1
        if OUT.read_text(encoding="utf-8") != rendered:
            print(f"{OUT} is stale -- run tools/gen-omnivoice-instruct-map.py", file=sys.stderr)
            return 1
        print(f"{OUT.name}: up to date ({len(rows)} items, {n_groups} categories)")
        return 0

    OUT.write_text(rendered, encoding="utf-8")
    print(f"wrote {OUT} ({len(rows)} items, {n_groups} categories)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
