#!/usr/bin/env python
"""Generate src/core/pinyin_data.inc — embedded pinyin tables for the F5-TTS
Chinese g2p (issue #294).

Mirrors the data pypinyin uses so the C++ `core_pinyin::convert_char_to_pinyin`
can reproduce F5-TTS's `convert_char_to_pinyin` (jieba + pypinyin TONE3 +
tone-sandhi) without a Python runtime.

Tables (all TONE3, tone-sandhi NOT applied — sandhi is applied in C++ at
runtime, exactly like pypinyin's post_pinyin):
  - single-char default reading  (PINYIN_DICT, first reading)
  - phrase readings              (PHRASES_DICT, per-char)

Run:  python tools/gen_pinyin_data.py --out src/core/pinyin_data.inc
Requires pypinyin (only at generation time; the .inc is checked in).
"""
import argparse
import sys
from pathlib import Path


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", type=Path, default=Path("src/core/pinyin_data.inc"))
    args = ap.parse_args()

    from pypinyin import lazy_pinyin, Style
    from pypinyin.constants import PINYIN_DICT, PHRASES_DICT

    # ── single-char default reading (TONE3, no sandhi) ──
    chars = []  # (codepoint, tone3)
    for cp in sorted(PINYIN_DICT.keys()):
        ch = chr(cp)
        py = lazy_pinyin(ch, style=Style.TONE3, tone_sandhi=False)
        if not py or not py[0]:
            continue
        s = py[0]
        # keep only entries that are plain ascii pinyin+digit (skip oddities)
        if not all(ord(c) < 128 for c in s):
            continue
        chars.append((cp, s))

    # ── phrases (TONE3 per char, no sandhi) ──
    phrases = []  # (phrase_str, "syl1 syl2 ...")
    for key in sorted(PHRASES_DICT.keys()):
        py = lazy_pinyin(key, style=Style.TONE3, tone_sandhi=False)
        if not py or not all(p and all(ord(c) < 128 for c in p) for p in py):
            continue
        # only phrases fully within the CJK range are useful for max-match seg
        if not all("㄀" <= c <= "鿿" for c in key):
            continue
        phrases.append((key, " ".join(py)))

    max_phrase_chars = max((len(k) for k, _ in phrases), default=1)

    def cstr(s: str) -> str:
        # emit a UTF-8 C string literal
        out = []
        for b in s.encode("utf-8"):
            if b == ord('"'):
                out.append('\\"')
            elif b == ord('\\'):
                out.append('\\\\')
            elif 32 <= b < 127:
                out.append(chr(b))
            else:
                out.append('\\x%02x' % b)
        return '"' + "".join(out) + '"'

    lines = []
    w = lines.append
    w("// Generated by tools/gen_pinyin_data.py — DO NOT EDIT.")
    w("// Pinyin tables for the F5-TTS Chinese g2p (#294). Source: pypinyin.")
    w("// TONE3, tone-sandhi applied at runtime (see pinyin_g2p.cpp).")
    w("")
    w("static const int PY_CHAR_N = %d;" % len(chars))
    w("static const int PY_PHRASE_N = %d;" % len(phrases))
    w("static const int PY_MAX_PHRASE_CHARS = %d;" % max_phrase_chars)
    w("")
    # char codepoints (sorted, ascending) + parallel pinyin
    w("static const unsigned int PY_CHAR_CP[] = {")
    for i in range(0, len(chars), 16):
        w("  " + ",".join(str(cp) for cp, _ in chars[i:i + 16]) + ",")
    w("};")
    w("static const char* const PY_CHAR_PY[] = {")
    for i in range(0, len(chars), 12):
        w("  " + ",".join(cstr(s) for _, s in chars[i:i + 12]) + ",")
    w("};")
    w("")
    # phrase keys (sorted by string) + parallel pinyin
    w("static const char* const PY_PHRASE_K[] = {")
    for i in range(0, len(phrases), 8):
        w("  " + ",".join(cstr(k) for k, _ in phrases[i:i + 8]) + ",")
    w("};")
    w("static const char* const PY_PHRASE_V[] = {")
    for i in range(0, len(phrases), 8):
        w("  " + ",".join(cstr(v) for _, v in phrases[i:i + 8]) + ",")
    w("};")
    w("")

    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text("\n".join(lines), encoding="utf-8")
    size = args.out.stat().st_size
    print(f"wrote {args.out}: chars={len(chars)} phrases={len(phrases)} "
          f"max_phrase_chars={max_phrase_chars} size={size/1e6:.2f} MB", file=sys.stderr)


if __name__ == "__main__":
    main()
