#!/usr/bin/env python
"""Generate src/chatterbox_nfkd_data.h from the Python unicodedata database.

The Chatterbox multilingual tokenizer (upstream MTLTokenizer.preprocess_text)
applies `unicodedata.normalize("NFKD", text.lower())` before tokenizing. The
C++ runtime must reproduce that NFKD step exactly or precomposed graphemes
(e.g. Arabic U+0623 ALEF-WITH-HAMZA) tokenize to a different id than the
model was trained on, producing spurious onset phonemes (issue #170).

This emits two sorted lookup tables:
  * decomposition: codepoint -> fully-recursive NFKD expansion (excludes the
    Hangul syllable block, which the runtime decomposes arithmetically).
  * combining class: codepoint -> canonical combining class (ccc != 0 only),
    used for the canonical-ordering pass.

Regenerate with:  python tools/gen_nfkd_table.py
Pinned to the Python build's Unicode version (printed in the header banner).
"""
import sys
import unicodedata

HANGUL_BASE = 0xAC00
HANGUL_END = 0xD7A3


def main():
    decomp = []
    for cp in range(0x110000):
        if HANGUL_BASE <= cp <= HANGUL_END:
            continue  # handled by the arithmetic Hangul path at runtime
        c = chr(cp)
        d = unicodedata.normalize("NFKD", c)
        if d != c:
            decomp.append((cp, [ord(x) for x in d]))

    ccc = [(cp, unicodedata.combining(chr(cp)))
           for cp in range(0x110000) if unicodedata.combining(chr(cp))]

    # Flat data array + per-key (offset, length).
    flat = []
    offsets = []
    for cp, cps in decomp:
        offsets.append((len(flat), len(cps)))
        flat.extend(cps)

    def emit_u32(name, vals):
        out = [f"static const uint32_t {name}[] = {{"]
        line = "    "
        for v in vals:
            tok = f"0x{v:X},"
            if len(line) + len(tok) > 100:
                out.append(line)
                line = "    "
            line += tok
        if line.strip():
            out.append(line)
        out.append("};")
        return "\n".join(out)

    def emit_u8(name, vals):
        out = [f"static const uint8_t {name}[] = {{"]
        line = "    "
        for v in vals:
            tok = f"{v},"
            if len(line) + len(tok) > 100:
                out.append(line)
                line = "    "
            line += tok
        if line.strip():
            out.append(line)
        out.append("};")
        return "\n".join(out)

    keys = [cp for cp, _ in decomp]
    off_flat = [o for o, _ in offsets]
    len_flat = [l for _, l in offsets]
    ccc_keys = [cp for cp, _ in ccc]
    ccc_vals = [v for _, v in ccc]

    parts = []
    parts.append("// Generated by tools/gen_nfkd_table.py — DO NOT EDIT BY HAND.")
    parts.append(f"// Unicode version: {unicodedata.unidata_version}")
    parts.append("// NFKD decomposition + canonical combining class tables for the")
    parts.append("// Chatterbox multilingual text preprocessor (issue #170).")
    parts.append("#pragma once")
    parts.append("#include <cstdint>")
    parts.append("// clang-format off")
    parts.append("namespace chatterbox_text_prep {")
    parts.append("namespace nfkd_data {")
    parts.append(f"static const int kDecompCount = {len(keys)};")
    parts.append(emit_u32("kDecompKeys", keys))
    parts.append(emit_u32("kDecompOffset", off_flat))
    parts.append(emit_u32("kDecompLen", len_flat))
    parts.append(emit_u32("kDecompData", flat))
    parts.append(f"static const int kCccCount = {len(ccc_keys)};")
    parts.append(emit_u32("kCccKeys", ccc_keys))
    parts.append(emit_u8("kCccVals", ccc_vals))
    parts.append("} // namespace nfkd_data")
    parts.append("} // namespace chatterbox_text_prep")
    parts.append("// clang-format on")
    parts.append("")

    sys.stdout.write("\n".join(parts))


if __name__ == "__main__":
    main()
