#!/bin/bash
# Upload pre-generated espeak-ng IPA dictionaries to HuggingFace.
# Run after `huggingface-cli login` or with HF_TOKEN set.
#
# These dicts are espeak-ng's IPA output for each word — factual
# phonetic data, not GPL-covered. Generated by tools/g2p_benchmark.py.
#
# Sizes:
#   EN: 126K words, 3 MB (from CMUdict vocabulary)
#   DE: 619K words, 23 MB (from open-dict-data single words)
#   ES: 600K words, 18 MB (from OLaPh ES)
#   FR: 258K words, ~6 MB (from OLaPh FR) [may be partial]

set -euo pipefail

DICT_DIR="${1:-/mnt/volume1/espeak-dicts}"
REPO="cstr/g2p-dicts"

echo "Uploading espeak dicts from $DICT_DIR to $REPO..."
for f in "$DICT_DIR"/espeak_*.tsv; do
    name=$(basename "$f")
    lines=$(wc -l < "$f")
    echo "  $name: $lines lines"
    huggingface-cli upload "$REPO" "$f" "$name" --repo-type dataset
done
echo "Done."
